export const workoutTemplateWithExercises = {
  id: 1,
  name: "Leg Day + Cardio Mix",
  type: "MULTIDAY",
  numDays: 3,
  description: "testing Leg Day + Cardio Mix",
  days: [
    {
      day_no: 1,
      day_date: "2025-02-01",
      is_rest_day: false,
      position: 1,
      exercises: [
        {
          name: "Barbell Squat",
          category: "legs",
          sets: 86,
          reps: 12,
          weight: 60,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Focus on full depth squats.",
          position: 2,
          groupType: null,
          groupId: null,
          _ui: {
            id: 1,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          }
        },
        {
          name: "Leg Press",
          category: "legs",
          sets: 53,
          reps: 15,
          weight: 180,
          distance: null,
          duration: null,
          rest_secs: 60,
          notes: "Keep feet shoulder-width apart.",
          position: 3,
          groupType: null,
          groupId: null,
          _ui: {
            id: 2,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          }
        },
        {
          name: "Treadmill Run",
          category: "cardio",
          sets: 37,
          reps: null,
          weight: null,
          distance: 3,
          duration: 20,
          rest_secs: 2,
          notes: "Maintain steady pace.",
          position: 4,
          groupType: null,
          groupId: null,
          _ui: {
            id: 3,
            hasReps: false,
            hasWeight: false,
            hasDistance: true,
            hasDuration: true,
          }
        },
        {
          name: "Rowing Machine",
          category: "cardio",
          sets: 24,
          reps: null,
          weight: 20,
          distance: 500,
          duration: 3,
          rest_secs: 45,
          notes: "Focus on form, drive with legs.",
          position: 5,
          groupType: "giant",
          groupId: "group-101",
          _ui: {
            id: 4,
            hasReps: false,
            hasWeight: true,
            hasDistance: true,
            hasDuration: true,
          }
        },
      ],
    },
    {
      day_no: 2,
      day_date: "2025-02-02",
      is_rest_day: false,
      position: 2,
      exercises: [
        {
          name: "Deadlift",
          category: "back",
          sets: 45,
          reps: 8,
          weight: 100,
          distance: null,
          duration: null,
          rest_secs: 120,
          notes: "Keep back straight, engage core.",
          position: 1,
          groupType: null,
          groupId: null,
          _ui: {
            id: 5,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          }
        },
      ],
    },
    {
      day_no: 3,
      day_date: "2025-02-03",
      is_rest_day: true,
      position: 3,
      exercises: [],
    },
  ],
};

export const workoutTemplatePushDay = {
  id: 2,
  name: "Push Day Strength",
  type: "MULTIDAY",
  numDays: 2,
  description: "testing Push Day Strength",
  days: [
    {
      day_no: 1,
      day_date: "2025-02-01",
      is_rest_day: false,
      position: 1,
      exercises: [
        {
          name: "Barbell Bench Press",
          category: "chest",
          sets: 45,
          reps: 12,
          weight: 70,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Focus on controlled reps, full ROM.",
          position: 1,
          groupType: null,
          groupId: null,
          _ui: {
            id: 1,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          }
        },
        {
          name: "Overhead Shoulder Press",
          category: "shoulders",
          sets: 46,
          reps: 12,
          weight: 40,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Keep core tight, avoid arching back.",
          position: 2,
          groupType: null,
          groupId: null,
          _ui: {
            id: 2,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          }
        },
        {
          name: "Tricep Dips",
          category: "triceps",
          sets: 47,
          reps: 12,
          weight: null,
          distance: null,
          duration: null,
          rest_secs: 60,
          notes: "Keep elbows close to body.",
          position: 3,
          groupType: null,
          groupId: null,
          _ui: {
            id: 3,
            hasReps: true,
            hasWeight: false,
            hasDistance: false,
            hasDuration: false,
          }
        },
      ],
    },
    {
      day_no: 2,
      day_date: "2025-02-02",
      is_rest_day: true,
      position: 2,
      exercises: [],
    },
  ],
};

export const workoutTemplateHIIT = {
  id: 3,
  name: "Full Body HIIT",
  type: "SINGLE",
  numDays: 1,
  description: "testing Full Body HIIT",
  days: [
    {
      day_no: 1,
      day_date: "2025-02-01",
      is_rest_day: false,
      position: 1,
      exercises: [
        {
          name: "Burpees",
          category: "fullbody",
          sets: 50,
          reps: 12,
          weight: null,
          distance: null,
          duration: null,
          rest_secs: 30,
          notes: "Explosive movement, maintain pace.",
          position: 1,
          groupType: null,
          groupId: null,
          _ui: {
            id: 1,
            hasReps: true,
            hasWeight: false,
            hasDistance: false,
            hasDuration: false,
          }
        },
        {
          name: "Mountain Climbers",
          category: "core",
          sets: 51,
          reps: null,
          weight: null,
          distance: null,
          duration: 30,
          rest_secs: 20,
          notes: "Drive knees fast, keep hips low.",
          position: 2,
          groupType: null,
          groupId: null,
          _ui: {
            id: 2,
            hasReps: false,
            hasWeight: false,
            hasDistance: false,
            hasDuration: true,
          }
        },
        {
          name: "Jump Squats",
          category: "legs",
          sets: 52,
          reps: 15,
          weight: null,
          distance: null,
          duration: null,
          rest_secs: 40,
          notes: "Land softly to protect knees.",
          position: 3,
          groupType: null,
          groupId: null,
          _ui: {
            id: 3,
            hasReps: true,
            hasWeight: false,
            hasDistance: false,
            hasDuration: false,
          }
        },
        {
          name: "Plank Hold",
          category: "core",
          sets: 53,
          reps: null,
          weight: null,
          distance: null,
          duration: 45,
          rest_secs: 30,
          notes: "Keep spine neutral, squeeze glutes.",
          position: 4,
          groupType: null,
          groupId: null,
          _ui: {
            id: 4,
            hasReps: false,
            hasWeight: false,
            hasDistance: false,
            hasDuration: true,
          }
        },
      ],
    },
  ],
};

export const TrainingList = [
  {
    id: 1,
    plan: {
      member_id: 33,
      name: "Push Day Strength",
      description: "Comprehensive push day workout",
      workout_type: "MULTIDAY",
      no_of_days: 2,
      start_date: "2025-02-01",
      end_date: "2025-02-02",
      created_by: 101,
      position: 1,
    },
    days: [
      {
        day_no: 1,
        day_date: "2025-02-01",
        is_rest_day: false,
        position: 1,
        exercises: [
          {
            name: "Barbell Bench Press",
            category: "chest",
            sets: 45,
            reps: 12,
            weight: 70,
            distance: null,
            duration: null,
            rest_secs: 90,
            notes: "Focus on controlled reps, full ROM.",
            position: 1,
            _ui: {
              id: 1,
              hasReps: true,
              hasWeight: true,
              hasDistance: false,
              hasDuration: false,
            }
          },
          {
            name: "Overhead Shoulder Press",
            category: "shoulders",
            sets: 46,
            reps: 12,
            weight: 40,
            distance: null,
            duration: null,
            rest_secs: 90,
            notes: "Keep core tight, avoid arching back.",
            position: 2,
            _ui: {
              id: 2,
              hasReps: true,
              hasWeight: true,
              hasDistance: false,
              hasDuration: false,
            }
          },
          {
            name: "Tricep Dips",
            category: "triceps",
            sets: 47,
            reps: 12,
            weight: null,
            distance: null,
            duration: null,
            rest_secs: 60,
            notes: "Keep elbows close to body.",
            position: 3,
            _ui: {
              id: 3,
              hasReps: true,
              hasWeight: false,
              hasDistance: false,
              hasDuration: false,
            }
          },
        ],
      },
      {
        day_no: 2,
        day_date: "2025-02-02",
        is_rest_day: true,
        position: 2,
        exercises: [],
      },
    ],
  },
  {
    id: 2,
    plan: {
      member_id: 501,
      name: "Treadmill",
      description: "Cardio training plan for endurance.",
      workout_type: "MULTIDAY",
      no_of_days: 3,
      start_date: "2025-09-03",
      end_date: "2025-09-05",
      created_by: 101,
      position: 2,
    },
    days: [
      {
        day_no: 1,
        day_date: "2025-09-03",
        is_rest_day: false,
        position: 1,
        exercises: [],
      },
      {
        day_no: 2,
        day_date: "2025-09-04",
        is_rest_day: false,
        position: 2,
        exercises: [],
      },
      {
        day_no: 3,
        day_date: "2025-09-05",
        is_rest_day: true,
        position: 3,
        exercises: [],
      },
    ],
  },
  {
    id: 3,
    plan: {
      member_id: 501,
      name: "Yoga Stretch",
      description: "Flexibility routine with yoga postures.",
      workout_type: "MULTIDAY",
      no_of_days: 2,
      start_date: "2025-09-05",
      end_date: "2025-09-06",
      created_by: 101,
      position: 3,
    },
    days: [
      {
        day_no: 1,
        day_date: "2025-09-05",
        is_rest_day: false,
        position: 1,
        exercises: [],
      },
      {
        day_no: 2,
        day_date: "2025-09-06",
        is_rest_day: false,
        position: 2,
        exercises: [],
      },
    ],
  },
];