import { FaCrown } from "react-icons/fa";

export const workoutPlansList = [
  {
    id: 1,
    exerciseCategory: "Strength Training",
    numberOfDays: 5,
    workoutName: "Bench Press",
    centerName: "Downtown Gym",
    createdDate: "2025-06-18",
    createdBy: "Admin",
  },
  {
    id: 2,
    exerciseCategory: "Cardio",
    numberOfDays: 5,
    workoutName: "Treadmill",
    centerName: "Fitness Center",
    createdDate: "2025-06-15",
    createdBy: "Admin",
  },
  {
    id: 3,
    exerciseCategory: "Flexibility",
    numberOfDays: 5,
    workoutName: "Yoga Stretch",
    centerName: "Zen Studio",
    createdDate: "2025-06-10",
    createdBy: "Admin",
  },
];

export const workoutTemplateWithExercises = {
  id: 1,
  name: "Leg Day + Cardio Mix",
  type: "MULTIDAY",
  numDays: 3,
  description: "testing Leg Day + Cardio Mix",
  days: [
    {
      day_no: 1,
      day_date: "2025-02-01",
      is_rest_day: false,
      position: 1,
      exercises: [
        {
          name: "Barbell Squat",
          category: "legs",
          sets: 86,
          reps: 12,
          weight_kg: 60,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Focus on full depth squats.",
          position: 2,
          groupType: null,
          groupId: null,
          _ui: {
            id: 1,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          },
        },
        {
          name: "Leg Press",
          category: "legs",
          sets: 53,
          reps: 15,
          weight_kg: 180,
          distance: null,
          duration: null,
          rest_secs: 60,
          notes: "Keep feet shoulder-width apart.",
          position: 3,
          groupType: null,
          groupId: null,
          _ui: {
            id: 2,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          },
        },
        {
          name: "Treadmill Run",
          category: "cardio",
          sets: 37,
          reps: null,
          weight_kg: null,
          distance: 3,
          duration: 20,
          rest_secs: 2,
          notes: "Maintain steady pace.",
          position: 4,
          groupType: null,
          groupId: null,
          _ui: {
            id: 3,
            hasReps: false,
            hasWeight: false,
            hasDistance: true,
            hasDuration: true,
          },
        },
        {
          name: "Rowing Machine",
          category: "cardio",
          sets: 24,
          reps: null,
          weight_kg: 20,
          distance: 500,
          duration: 3,
          rest_secs: 45,
          notes: "Focus on form, drive with legs.",
          position: 5,
          _ui: {
            id: 4,
            hasReps: false,
            hasWeight: true,
            hasDistance: true,
            hasDuration: true,
          },
        },
      ],
    },
    {
      day_no: 2,
      day_date: "2025-02-02",
      is_rest_day: false,
      position: 2,
      exercises: [
        {
          name: "Deadlift",
          category: "back",
          sets: 45,
          reps: 8,
          weight_kg: 100,
          distance: null,
          duration: null,
          rest_secs: 120,
          notes: "Keep back straight, engage core.",
          position: 1,
          groupType: null,
          groupId: null,
          _ui: {
            id: 5,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          },
        },
      ],
    },
    {
      day_no: 3,
      day_date: "2025-02-03",
      is_rest_day: true,
      position: 3,
      exercises: [],
    },
  ],
};

export const workoutTemplatePushDay = {
  id: 2,
  name: "Push Day Strength",
  type: "MULTIDAY",
  numDays: 2,
  description: "testing Push Day Strength",
  days: [
    {
      day_no: 1,
      day_date: "2025-02-01",
      is_rest_day: false,
      position: 1,
      exercises: [
        {
          name: "Barbell Bench Press",
          category: "chest",
          sets: 45,
          reps: 12,
          weight_kg: 70,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Focus on controlled reps, full ROM.",
          position: 1,
          groupType: null,
          groupId: null,
          _ui: {
            id: 1,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          },
        },
        {
          name: "Overhead Shoulder Press",
          category: "shoulders",
          sets: 46,
          reps: 12,
          weight_kg: 40,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Keep core tight, avoid arching back.",
          position: 2,
          groupType: null,
          groupId: null,
          _ui: {
            id: 2,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          },
        },
        {
          name: "Tricep Dips",
          category: "triceps",
          sets: 47,
          reps: 12,
          weight_kg: null,
          distance: null,
          duration: null,
          rest_secs: 60,
          notes: "Keep elbows close to body.",
          position: 3,
          groupType: null,
          groupId: null,
          _ui: {
            id: 3,
            hasReps: true,
            hasWeight: false,
            hasDistance: false,
            hasDuration: false,
          },
        },
      ],
    },
    {
      day_no: 2,
      day_date: "2025-02-02",
      is_rest_day: true,
      position: 2,
      exercises: [],
    },
  ],
};

export const TrainingList = {
  id: 3,
  name: "Cardio Workout",
  type: "MULTIDAY",
  numDays: 2,
  description: "Comprehensive push day workout",
  days: [
    {
      day_no: 1,
      day_date: "2025-02-01",
      is_rest_day: false,
      position: 1,
      exercises: [
        {
          name: "Barbell Bench Press",
          category: "chest",
          sets: 45,
          reps: 12,
          weight_kg: 70,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Focus on controlled reps, full ROM.",
          position: 1,
          _ui: {
            id: 1,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          },
        },
        {
          name: "Overhead Shoulder Press",
          category: "shoulders",
          sets: 46,
          reps: 12,
          weight_kg: 40,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Keep core tight, avoid arching back.",
          position: 2,
          _ui: {
            id: 2,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          },
        },
        {
          name: "Tricep Dips",
          category: "triceps",
          sets: 47,
          reps: 12,
          weight_kg: null,
          distance: null,
          duration: null,
          rest_secs: 60,
          notes: "Keep elbows close to body.",
          position: 3,
          _ui: {
            id: 3,
            hasReps: true,
            hasWeight: false,
            hasDistance: false,
            hasDuration: false,
          },
        },
      ],
    },
    {
      day_no: 2,
      day_date: "2025-02-02",
      is_rest_day: true,
      position: 2,
      exercises: [],
    },
  ],
};

export const workoutTemplateHIIT = {
  id: 4,
  name: "Full Body HIIT",
  type: "SINGLE",
  numDays: 1,
  description: "testing Full Body HIIT",
  days: [
    {
      day_no: 1,
      day_date: "2025-02-01",
      is_rest_day: false,
      position: 1,
      exercises: [
        {
          name: "Barbell Bench Press",
          category: "chest",
          sets: 45,
          reps: 12,
          weight_kg: 70,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Focus on controlled reps, full ROM.",
          position: 1,
          _ui: {
            id: 1,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          },
        },
        {
          name: "Overhead Shoulder Press",
          category: "shoulders",
          sets: 46,
          reps: 12,
          weight_kg: 40,
          distance: null,
          duration: null,
          rest_secs: 90,
          notes: "Keep core tight, avoid arching back.",
          position: 2,
          _ui: {
            id: 2,
            hasReps: true,
            hasWeight: true,
            hasDistance: false,
            hasDuration: false,
          },
        },
        {
          name: "Tricep Dips",
          category: "triceps",
          sets: 47,
          reps: 12,
          weight_kg: null,
          distance: null,
          duration: null,
          rest_secs: 60,
          notes: "Keep elbows close to body.",
          position: 3,
          _ui: {
            id: 3,
            hasReps: true,
            hasWeight: false,
            hasDistance: false,
            hasDuration: false,
          },
        },
      ],
    },
    
  ],
};

export const memberMockData = [
  {
    id: 1,
    memberId: "M001",
    name: "John Doe",
    membershipType: "Gold",
    memberFrom: "2024-05-01",
    memberTill: "2025-05-01",
    trainer: "Trainer A",
    trainerType: "PT",
    fohAssigned: "FOH A",
  },
  {
    id: 2,
    memberId: "M002",
    name: "Jane Smith",
    membershipType: "Silver",
    memberFrom: "2024-06-15",
    memberTill: "2024-12-15",
    trainer: "Trainer B",
    trainerType: "GT",
    fohAssigned: "FOH B",
  },
  {
    id: 3,
    memberId: "M003",
    name: "Alice Johnson",
    membershipType: "Platinum",
    memberFrom: "2024-01-10",
    memberTill: "2025-01-10",
    trainer: "Trainer C",
    trainerType: "Nutrition",
    fohAssigned: "FOH C",
  },
  {
    id: 4,
    memberId: "M004",
    name: "Michael Brown",
    membershipType: "Gold",
    memberFrom: "2024-03-01",
    memberTill: "2025-03-01",
    trainer: "Trainer A",
    trainerType: "PT",
    fohAssigned: "FOH B",
  },
  {
    id: 5,
    memberId: "M005",
    name: "Emily Davis",
    membershipType: "Silver",
    memberFrom: "2024-07-01",
    memberTill: "2024-10-01",
    trainer: "Trainer B",
    trainerType: "GT",
    fohAssigned: "FOH C",
  },
  {
    id: 6,
    memberId: "M006",
    name: "William Martinez",
    membershipType: "Platinum",
    memberFrom: "2023-11-20",
    memberTill: "2024-11-20",
    trainer: "Trainer C",
    trainerType: "Nutrition",
    fohAssigned: "FOH A",
  },
  {
    id: 7,
    memberId: "M007",
    name: "Olivia Wilson",
    membershipType: "Gold",
    memberFrom: "2024-08-05",
    memberTill: "2025-08-05",
    trainer: "Trainer A",
    trainerType: "PT",
    fohAssigned: "FOH B",
  },
  {
    id: 8,
    memberId: "M008",
    name: "James Taylor",
    membershipType: "Silver",
    memberFrom: "2024-02-01",
    memberTill: "2024-08-01",
    trainer: "Trainer B",
    trainerType: "GT",
    fohAssigned: "FOH C",
  },
  {
    id: 9,
    memberId: "M009",
    name: "Sophia Anderson",
    membershipType: "Platinum",
    memberFrom: "2024-04-01",
    memberTill: "2025-04-01",
    trainer: "Trainer C",
    trainerType: "Nutrition",
    fohAssigned: "FOH A",
  },
  {
    id: 10,
    memberId: "M010",
    name: "Daniel Thomas",
    membershipType: "Gold",
    memberFrom: "2024-09-15",
    memberTill: "2025-09-15",
    trainer: "Trainer A",
    trainerType: "PT",
    fohAssigned: "FOH B",
  },
];

export const followUpsData = [
  {
    id: 1,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 2,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Attempted",
    type: "enquiry calls",
  },
  {
    id: 3,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Contacted",
    type: "welcome calls",
  },
  {
    id: 4,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 5,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 6,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
];

export const leadList = [
  {
    id: 1,
    leadId: "L001",
    createdOn: "01-06-2025",
    lastUpdated: "08-06-2025",
    name: "John Doe",
    leadSource: "Website",
    leadStatus: "Open",
    leadStage: "Enquiry",
    lastCallStatus: "New",
    leadOwner: "Alice Johnson",
    action: "Follow Up",
  },
  {
    id: 2,
    leadId: "L002",
    createdOn: "02-06-2025",
    lastUpdated: "09-06-2025",
    name: "Jane Smith",
    leadSource: "Referral",
    leadStatus: "In Progress",
    leadStage: "Trial Scheduled",
    lastCallStatus: "Trial Scheduled",
    leadOwner: "Bob Thompson",
    action: "Schedule Demo",
  },
  {
    id: 3,
    leadId: "L003",
    createdOn: "03-06-2025",
    lastUpdated: "06-06-2025",
    name: "Sam Lee",
    leadSource: "Social Media",
    leadStatus: "Closed",
    leadStage: "Won",
    lastCallStatus: "Won",
    leadOwner: "Cara White",
    action: "Send Invoice",
  },
  {
    id: 4,
    leadId: "L004",
    createdOn: "04-06-2025",
    lastUpdated: "07-06-2025",
    name: "Mike Chen",
    leadSource: "Email Campaign",
    leadStatus: "Open",
    leadStage: "Post Trial",
    lastCallStatus: "Post Trial Follow-up",
    leadOwner: "Derek Miles",
    action: "Call Back",
  },
  {
    id: 5,
    leadId: "L005",
    createdOn: "05-06-2025",
    lastUpdated: "08-06-2025",
    name: "Anna Patel",
    leadSource: "LinkedIn",
    leadStatus: "Lost",
    leadStage: "Lost",
    lastCallStatus: "Not Interested",
    leadOwner: "Emily Watson",
    action: "Mark as Lost",
  },
  {
    id: 6,
    leadId: "L006",
    createdOn: "06-06-2025",
    lastUpdated: "09-06-2025",
    name: "Carlos Rivera",
    leadSource: "Google Ads",
    leadStatus: "Open",
    leadStage: "Enquiry",
    lastCallStatus: "Follow-up",
    leadOwner: "Nina Brown",
    action: "Send Email",
  },
  {
    id: 7,
    leadId: "L007",
    createdOn: "07-06-2025",
    lastUpdated: "09-06-2025",
    name: "Fatima Noor",
    leadSource: "Facebook Ads",
    leadStatus: "In Progress",
    leadStage: "Trial Scheduled",
    lastCallStatus: "Busy Tone",
    leadOwner: "Zack Lee",
    action: "Retry Call",
  },
  {
    id: 8,
    leadId: "L008",
    createdOn: "08-06-2025",
    lastUpdated: "09-06-2025",
    name: "George Knight",
    leadSource: "Direct Visit",
    leadStatus: "Closed",
    leadStage: "Won",
    lastCallStatus: "Switched Off/ Out of Reach",
    leadOwner: "Linda Marks",
    action: "Send Contract",
  },
  {
    id: 9,
    leadId: "L009",
    createdOn: "01-06-2025",
    lastUpdated: "04-06-2025",
    name: "Isabella Rossi",
    leadSource: "Cold Call",
    leadStatus: "Open",
    leadStage: "Enquiry",
    lastCallStatus: "Future Prospect",
    leadOwner: "Raj Mehta",
    action: "Nurture Lead",
  },
  {
    id: 10,
    leadId: "L010",
    createdOn: "09-06-2025",
    lastUpdated: "09-06-2025",
    name: "Tom Berg",
    leadSource: "Trade Show",
    leadStatus: "In Progress",
    leadStage: "Post Trial",
    lastCallStatus: "No Answer",
    leadOwner: "Sofia Green",
    action: "Send Reminder",
  },
];

export const assignedLeadsData = [
  {
    id: 1,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 2,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Attempted",
    type: "enquiry calls",
  },
  {
    id: 3,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Contacted",
    type: "welcome calls",
  },
  {
    id: 4,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 5,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 6,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
];

export const trialScheduledUsers = [
  {
    id: 1,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 2,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 3,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
];

export const groupClasses = {
  chart: {
    type: "column",
    height: 400,
  },
  title: {
    text: "Group Classes Statistics",
    align: "left",
    style: {
      fontSize: "16px",
      fontWeight: "600",
    },
  },
  credits: {
    enabled: false,
  },
  xAxis: {
    categories: ["1 Apr", "2 Apr", "3 Apr", "4 Apr", "5 Apr", "6 Apr", "7 Apr"],
    title: { text: null },
  },
  yAxis: {
    min: 0,
    title: {
      text: null,
    },
    stackLabels: {
      enabled: false,
      style: {
        fontWeight: "bold",
        color: "red",
      },
    },
  },
  legend: {
    align: "right",
    verticalAlign: "top",
    layout: "horizontal",
    symbolRadius: 6,
    itemStyle: {
      fontWeight: "normal",
      fontSize: "13px",
    },
    labelFormatter: function () {
      const colors = {
        Cancellations: "#6b6b6b",
        Reservations: "#bcbcbc",
        Bookings: "#e0e0e0",
      };
      return `<span style="color: ${colors[this.name]}">${this.name}</span>`;
    },
    useHTML: true,
  },
  tooltip: {
    shared: true,
    pointFormat:
      '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b><br/>',
  },
  plotOptions: {
    column: {
      stacking: "normal",
      dataLabels: {
        enabled: false,
      },
    },
  },
  series: [
    {
      name: "Cancellations",
      data: [20, 10, 25, 10, 10, 15, 15],
      color: "#6b6b6b",
    },
    {
      name: "Reservations",
      data: [15, 10, 20, 15, 15, 20, 20],
      color: "#bcbcbc",
    },
    {
      name: "Bookings",
      data: [5, 10, 20, 10, 10, 15, 15],
      color: "#e0e0e0",
    },
  ],
};

export const servicesName = [
  { value: "membership plan", label: "Membership Plan" },
  { value: "personal training", label: "Personal Training" },
  { value: "thrive membership fee", label: "Thrive Membership Fee" },
  { value: "miscellaneous fee", label: "Miscellaneous Fee" },
  { value: "nutrition packages", label: "Nutrition Packages" },
  { value: "event", label: "Event" },
];

export const leadsSources = [
  { value: "hoardings", label: "Hoardings" },
  { value: "google", label: "Google" },
  { value: "social media", label: "Social Media" },
  { value: "referral", label: "Referral" },
  { value: "corporate", label: "Corporate" },
  { value: "word of mouth", label: "Word of Mouth" },
  { value: "thrive app", label: "Thrive App" },
  { value: "website", label: "Website" },
  { value: "events / campaigns", label: "Events / Campaigns" },
  { value: "corporate outreach", label: "Corporate Outreach" },
  { value: "qr code", label: "QR Code" },
];

export const leadTypes = [
  { value: "walk-in", label: "Walk-in" },
  { value: "in-bound", label: "In-bound" },
  { value: "outbound", label: "Outbound" },
  { value: "email", label: "Email" },
  { value: "whatsApp", label: "WhatsApp" },
];

export const centreInfo = [
  {
    value: "centre-1",
    label: "Centre 1",
    state: "Maharashtra",
    country: "India",
  },
  { value: "centre-2", label: "Centre 2", state: "California", country: "USA" },
  {
    value: "centre-3",
    label: "Centre 3",
    state: "New South Wales",
    country: "Australia",
  },
];

export const leadSubTypes = [
  { value: "in-bound", label: "In-bound" },
  { value: "outbound", label: "Outbound" },
];

export const dummyServices = [
  {
    id: 1,
    status: "Active",
    serviceName: "Premium Fitness Plan",
    serviceVariation: "Personal Training",
    serviceId: "SVC-001",
    duration: "3 Months",
    price: "₹5000",
    sessions: 10,
    sessionsTaken: 5,
    lastVisited: "2025-04-24",
    thriveCoins: 50,
    countdown: "80 Days",
    startDate: "2025-01-15",
    endDate: "2025-04-15",
  },
  {
    id: 2,
    status: "Expired",
    serviceName: "Yoga Session Package",
    serviceVariation: "Group Yoga",
    serviceId: "SVC-002",
    duration: "1 Month",
    price: "₹2000",
    sessions: 8,
    sessionsTaken: 8,
    lastVisited: "2025-03-10",
    thriveCoins: 20,
    countdown: "Expired",
    startDate: "2025-02-01",
    endDate: "2025-03-01",
  },
  {
    id: 3,
    status: "Active",
    serviceName: "Premium Fitness Plan",
    serviceVariation: "Personal Training",
    serviceId: "SVC-001",
    duration: "3 Months",
    price: "₹5000",
    sessions: 10,
    sessionsTaken: 5,
    lastVisited: "2025-04-24",
    thriveCoins: 50,
    countdown: "80 Days",
    startDate: "2025-01-15",
    endDate: "2025-04-15",
  },
  {
    id: 4,
    status: "Active",
    serviceName: "Premium Fitness Plan",
    serviceVariation: "Personal Training",
    serviceId: "SVC-001",
    duration: "3 Months",
    price: "₹5000",
    sessions: 10,
    sessionsTaken: 5,
    lastVisited: "2025-04-24",
    thriveCoins: 50,
    countdown: "80 Days",
    startDate: "2025-01-15",
    endDate: "2025-04-15",
  },
];

export const assignLead = [
  {
    id: 1,
    attendance_card_number: null,
    firstname: "John",
    lastname: "Doe",
    country_code: "+1",
    mobile: "1234567890",
    email: "john.doe@example.com",
    gender: "MALE",
    date_of_birth: "1990-01-01",
    age: 35,
    address: "123 Street Name",
    location: "New York",
    profile_pic: null,
    company_name: "Example Inc",
    activity_level: "Active",
    weight: "70",
    weight_type: "KG",
    height: "5.9",
    height_type: "FT",
    target_weight: "68",
    target_weight_type: "KG",
    designation: "Manager",
    is_kyc: true,
    lead_type: "Phone",
    lead_source: "Website",
    lead_status: "New",
    created_by: "admin",
    interested_in: "Membership",
    platform: "Instagram",
    club_id: 1,
    createdAt: "2025-09-01T08:00:00.000Z",
    updatedAt: "2025-09-01T08:00:00.000Z",
    last_call_status: "Interested",
  },
  {
    id: 2,
    attendance_card_number: null,
    firstname: "Jane",
    lastname: "Smith",
    country_code: "+44",
    mobile: "9876543210",
    email: "jane.smith@example.com",
    gender: "FEMALE",
    date_of_birth: "1985-05-20",
    age: 40,
    address: "456 Avenue",
    location: "London",
    profile_pic: null,
    company_name: "Tech Solutions",
    activity_level: "Moderate",
    weight: "65",
    weight_type: "KG",
    height: "5.6",
    height_type: "FT",
    target_weight: "60",
    target_weight_type: "KG",
    designation: "Engineer",
    is_kyc: false,
    lead_type: "Walk-in",
    lead_source: "Referral",
    lead_status: "Opportunity",
    created_by: "system",
    interested_in: "Training",
    platform: "LinkedIn",
    club_id: 2,
    createdAt: "2025-09-01T08:10:00.000Z",
    updatedAt: "2025-09-01T08:15:00.000Z",
    last_call_status: "Follow-up Needed",
  },
  {
    id: 3,
    attendance_card_number: null,
    firstname: "Alice",
    lastname: "Johnson",
    country_code: "+91",
    mobile: "8888888888",
    email: "alice.j@example.com",
    gender: "FEMALE",
    date_of_birth: "1992-07-12",
    age: 33,
    address: "789 Road",
    location: "Delhi",
    profile_pic: null,
    company_name: "Startup Hub",
    activity_level: "Low",
    weight: "58",
    weight_type: "KG",
    height: "5.4",
    height_type: "FT",
    target_weight: "55",
    target_weight_type: "KG",
    designation: "Developer",
    is_kyc: true,
    lead_type: "In-bound Call",
    lead_source: "Social Media",
    lead_status: "Contacted",
    created_by: "agent1",
    interested_in: "Consultation",
    platform: "Facebook",
    club_id: 3,
    createdAt: "2025-09-01T08:20:00.000Z",
    updatedAt: "2025-09-01T08:25:00.000Z",
    last_call_status: "Pending",
  },
  {
    id: 4,
    attendance_card_number: null,
    firstname: "Bob",
    lastname: "Brown",
    country_code: "+61",
    mobile: "7777777777",
    email: "bob.brown@example.com",
    gender: "MALE",
    date_of_birth: "1988-03-05",
    age: 37,
    address: "100 Main St",
    location: "Sydney",
    profile_pic: null,
    company_name: "Global Corp",
    activity_level: "Active",
    weight: "80",
    weight_type: "KG",
    height: "6.0",
    height_type: "FT",
    target_weight: "75",
    target_weight_type: "KG",
    designation: "Analyst",
    is_kyc: false,
    lead_type: "App",
    lead_source: "Email Campaign",
    lead_status: "New",
    created_by: "marketing_team",
    interested_in: "Nutrition",
    platform: "Email",
    club_id: 4,
    createdAt: "2025-09-01T08:30:00.000Z",
    updatedAt: "2025-09-01T08:30:00.000Z",
    last_call_status: "Scheduled",
  },
  {
    id: 5,
    attendance_card_number: null,
    firstname: "Charlie",
    lastname: "White",
    country_code: "+81",
    mobile: "6666666666",
    email: "charlie.white@example.com",
    gender: "NOTDISCLOSE",
    date_of_birth: "1995-11-11",
    age: 30,
    address: "111 River Side",
    location: "Tokyo",
    profile_pic: null,
    company_name: "Health First",
    activity_level: "High",
    weight: "75",
    weight_type: "KG",
    height: "5.8",
    height_type: "FT",
    target_weight: "70",
    target_weight_type: "KG",
    designation: "Consultant",
    is_kyc: true,
    lead_type: "WhatsApp",
    lead_source: "Flyer",
    lead_status: "Opportunity",
    created_by: "reception",
    interested_in: "Yoga",
    platform: "WhatsApp",
    club_id: 5,
    createdAt: "2025-09-01T08:35:00.000Z",
    updatedAt: "2025-09-01T08:35:00.000Z",
    last_call_status: "Not Interested",
  },
  {
    id: 6,
    attendance_card_number: null,
    firstname: "David",
    lastname: "Lee",
    country_code: "+49",
    mobile: "5555555555",
    email: "david.lee@example.com",
    gender: "MALE",
    date_of_birth: "1993-09-09",
    age: 32,
    address: "222 Forest Road",
    location: "Berlin",
    profile_pic: null,
    company_name: "TechWave",
    activity_level: "Low",
    weight: "72",
    weight_type: "KG",
    height: "6.1",
    height_type: "FT",
    target_weight: "70",
    target_weight_type: "KG",
    designation: "Product Manager",
    is_kyc: false,
    lead_type: "Walk-in",
    lead_source: "Billboard",
    lead_status: "New",
    created_by: "admin",
    interested_in: "Weight Loss",
    platform: "Instagram",
    club_id: 6,
    createdAt: "2025-09-01T08:40:00.000Z",
    updatedAt: "2025-09-01T08:40:00.000Z",
    last_call_status: "Call Back Later",
  },
];

export const companies = [
  { value: "ba-continuum-india-pvt-ltd", label: "BA CONTINUUM INDIA PVT LTD" },
  {
    value: "masters-union-shanti-informatics",
    label: "MASTERS UNION-SHANTI INFORMATICS",
  },
  {
    value: "wpp-marketing-communications-india-p-ltd",
    label: "WPP MARKETING COMMUNICATIONS INDIA P LTD",
  },
  {
    value: "simpliwork-offices-private-limited-arcesium",
    label: "SIMPLIWORK OFFICES PRIVATE LIMITED (ARCESIUM)",
  },
  {
    value: "ey-global-delivery-services-india-llp",
    label: "EY GLOBAL DELIVERY SERVICES INDIA LLP",
  },
  {
    value: "reckitt-benckiser-india-private-ltd",
    label: "RECKITT BENCKISER (INDIA) PRIVATE LTD",
  },
  {
    value: "expedia-online-travel-services-i-p-ltd",
    label: "EXPEDIA ONLINE TRAVEL SERVICES(I) P LTD",
  },
  { value: "campus-active-pvt-ltd", label: "Campus Active Pvt Ltd" },
  { value: "jll", label: "JLL" },
  {
    value: "aviva-life-insurance-company-india-ltd",
    label: "AVIVA LIFE INSURANCE COMPANY INDIA LTD",
  },
  { value: "trilegal", label: "TRILEGAL" },
  { value: "siemens-limited", label: "SIEMENS LIMITED" },
  {
    value: "the-boston-consulting-group-i-pvt-ltd",
    label: "THE BOSTON CONSULTING GROUP (I) PVT LTD",
  },
  { value: "pernod-ricard-india-p-ltd", label: "PERNOD RICARD INDIA (P) LTD." },
  {
    value: "gartner-india-research-advisory-services-pr",
    label: "GARTNER INDIA RESEARCH & ADVISORY SERVICES PR",
  },
  { value: "nab", label: "NAB" },
  {
    value: "agoda-international-india-private-ltd",
    label: "AGODA INTERNATIONAL INDIA PRIVATE LTD.",
  },
  { value: "dr-morepen-limited", label: "DR MOREPEN LIMITED" },
  {
    value: "ipm-india-wholesale-trading-private-limited",
    label: "IPM INDIA WHOLESALE TRADING PRIVATE LIMTED",
  },
  { value: "morepen-laboratories-ltd", label: "MOREPEN LABORATORIES LTD" },
  { value: "volvo-auto-india-pvt-ltd", label: "VOLVO AUTO INDIA PVT . LTD" },
  {
    value: "samsung-india-electronics-private-ltd",
    label: "SAMSUNG INDIA ELECTRONICS PRIVATE LTD",
  },
  { value: "apple-india-pvt-ltd", label: "APPLE INDIA PVT. LTD." },
  { value: "hdfc", label: "HDFC" },
  {
    value: "petrofac-engg-services-india-pvt-ltd",
    label: "Petrofac Engg Services India Pvt Ltd",
  },
];

export const mockData = [
  {
    id: 1,
    status: "active",
    leadStatus: "new",
    serviceName: "Membership Plan",
    gender: "male",
    serviceVariation: "1 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Kritika",
    assignedLead: "",
    generalTrainer: "Ravinder",
    leadSource: "Google",
    invoice: "Not Billed Members",
    serviceCategory: "Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Sport",
    customGroups: "Group A",
    enquiryId: 3999601,
    email: "janani.singh@gmail.com",
    dob: "01-01-1990",
    age: "34",
    address: "DLF Phase 3, Gurgaon",
    contact: "+918700704309",
    locality: "gurgaon",
    company: "Google India",
    emergencyName: "Aarav Singh",
    emergencyContact: "+919111111111",
    emergencyRelation: "Brother",
    createdOn: "20-04-2025",
    name: "Janani Singh",
    leadType: "phone", // mockType: phone
    enquiryStage: "Enquiry",
    lastUpdated: "24-04-2025",
    callTag: "Hot",
    staff: "Preeti",
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
    ptSessions: 0,
    trainersList: [{ name: "Deepak", id: 858 }],
  },
  {
    id: 2,
    status: "inactive",
    leadStatus: "lost",
    serviceName: "Membership Plan",
    gender: "female",
    serviceVariation: "1 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Kritika",
    assignedLead: "",
    generalTrainer: "Ravinder",
    leadSource: "Google",
    invoice: "Not Billed Members",
    serviceCategory: "Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Sport",
    customGroups: "Group A",
    enquiryId: 3999602,
    email: "iftekhar.khan@gmail.com",
    dob: "14-02-1988",
    age: "37",
    address: "Sector 45, Noida",
    contact: "+919911216853",
    locality: "gurgaon",
    company: "Google India",
    emergencyName: "Aarav Singh",
    emergencyContact: "+919111111111",
    emergencyRelation: "Brother",
    createdOn: "20-04-2025",
    name: "Iftekhar Khan",
    leadType: "phone", // mockType: phone
    enquiryStage: "Enquiry",
    lastUpdated: "24-04-2025",
    callTag: "Hot",
    staff: "Preeti",
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
    trainersList: [{ name: "Deepak", id: 858 }],
    ptSessions: 0,
  },
  {
    id: 3,
    status: "active",
    leadStatus: "closed",
    serviceName: "Personal Training",
    gender: "Not Specified",
    serviceVariation: "1 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Ravinder",
    assignedLead: "",
    generalTrainer: "Kritika",
    leadSource: "Corporate",
    invoice: "Not Billed Members",
    serviceCategory: "PT Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Fat Loss",
    customGroups: "Group C",
    enquiryId: 3999603,
    email: "megha.patel@example.com",
    dob: "05-07-1993",
    age: "31",
    address: "MG Road, Bengaluru",
    contact: "+918765432109",
    locality: "Bengaluru",
    company: "Flipkart",
    emergencyName: "Ravi Patel",
    emergencyContact: "+919333333333",
    emergencyRelation: "Husband",
    createdOn: "22-04-2025",
    name: "Megha Patel",
    leadType: "website", // mockType: website
    enquiryStage: "Enquiry",
    lastUpdated: "26-04-2025",
    callTag: "Cold",
    staff: "Anuj",
    profileImage: "https://randomuser.me/api/portraits/women/32.jpg",
    ptSessions: 0,
  },
  {
    id: 4,
    status: "active",
    leadStatus: "closed",
    serviceName: "Membership Plan",
    gender: "female",
    serviceVariation: "6 Month",
    ageGroup: "5-8 years",
    salesRep: "Ravinder",
    memberManager: "Kritika",
    assignedLead: "",
    generalTrainer: "Ravinder",
    leadSource: "Google",
    invoice: "Expired Invoice",
    serviceCategory: "Trial",
    purchaseType: "Events",
    behaviourBased: "Irregular Member",
    fitnessGoal: "Sport",
    customGroups: "Group D",
    enquiryId: 3999604,
    email: "rohan.mehta@gmail.com",
    dob: "30-10-1990",
    age: "34",
    address: "Bandra West, Mumbai",
    contact: "+918888880000",
    locality: "Mumbai",
    company: "Tata Consultancy",
    emergencyName: "Neha Mehta",
    emergencyContact: "+919444444444",
    emergencyRelation: "Wife",
    createdOn: "23-04-2025",
    name: "Rohan Mehta",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "27-04-2025",
    callTag: "Hot",
    staff: "Ritika",
    profileImage: "https://randomuser.me/api/portraits/men/21.jpg",
    ptSessions: 0,
  },
  {
    id: 5,
    status: "active",
    leadStatus: "lost",
    serviceName: "Membership Plan",
    gender: "male",
    serviceVariation: "6 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Kritika",
    assignedLead: "",
    generalTrainer: "Kritika",
    leadSource: "Email",
    invoice: "Not Billed Members",
    serviceCategory: "Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Sport",
    customGroups: "Group E",
    enquiryId: 3999605,
    email: "sneha.jain@yahoo.com",
    dob: "12-03-1996",
    age: "29",
    address: "South Ex, Delhi",
    contact: "+917777777777",
    locality: "New Delhi",
    company: "Zomato",
    emergencyName: "Priya Jain",
    emergencyContact: "+919555555555",
    emergencyRelation: "Sister",
    createdOn: "24-04-2025",
    name: "Sneha Jain",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "28-04-2025",
    callTag: "Warm",
    staff: "Manish",
    profileImage: "https://randomuser.me/api/portraits/women/28.jpg",
    ptSessions: 3,
  },
  {
    id: 6,
    status: "active",
    leadStatus: "won",
    serviceName: "Membership Plan",
    gender: "male",
    serviceVariation: "1 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Kritika",
    assignedLead: "",
    generalTrainer: "Ravinder",
    leadSource: "Google",
    invoice: "Not Billed Members",
    serviceCategory: "Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Sport",
    customGroups: "Group A",
    enquiryId: 3999606,
    email: "akash.verma@hotmail.com",
    dob: "22-11-1991",
    age: "33",
    address: "Park Street, Kolkata",
    contact: "+919999999999",
    locality: "Kolkata",
    company: "Wipro",
    emergencyName: "Ritika Verma",
    emergencyContact: "+919666666666",
    emergencyRelation: "Sister",
    createdOn: "19-04-2025",
    name: "Akash Verma",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "23-04-2025",
    callTag: "Cold",
    staff: "Prerna",
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
    ptSessions: 9,
  },
  {
    id: 7,
    status: "active",
    leadStatus: "opportunity",
    serviceName: "Personal Training",
    gender: "female",
    serviceVariation: "6 Month",
    ageGroup: "5-8 years",
    salesRep: "Ravinder",
    memberManager: "Ravinder",
    assignedLead: "",
    generalTrainer: "Kritika",
    leadSource: "Email",
    invoice: "Expired Invoice",
    serviceCategory: "PT Trial",
    purchaseType: "Events",
    behaviourBased: "Irregular Member",
    fitnessGoal: "Fat Loss",
    customGroups: "Group B",
    enquiryId: 3999607,
    email: "nisha.rajan@gmail.com",
    dob: "09-06-1994",
    age: "30",
    address: "Vashi, Navi Mumbai",
    contact: "+918100010001",
    locality: "Navi Mumbai",
    company: "Amazon India",
    emergencyName: "Kavya Rajan",
    emergencyContact: "+919777777777",
    emergencyRelation: "Mother",
    createdOn: "18-04-2025",
    name: "Nisha Rajan",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "21-04-2025",
    callTag: "Warm",
    staff: "Alok",
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
    ptSessions: 10,
  },
  {
    id: 8,
    status: "inactive",
    leadStatus: "opportunity",
    serviceName: "Personal Training",
    gender: "female",
    serviceVariation: "6 Month",
    ageGroup: "5-8 years",
    salesRep: "Ravinder",
    memberManager: "Ravinder",
    assignedLead: "assigned",
    generalTrainer: "Kritika",
    leadSource: "Email",
    invoice: "Expired Invoice",
    serviceCategory: "PT Trial",
    purchaseType: "Events",
    behaviourBased: "Irregular Member",
    fitnessGoal: "Fat Loss",
    customGroups: "Group B",
    enquiryId: 3999608,
    email: "rahul.deshmukh@outlook.com",
    dob: "25-12-1985",
    age: "39",
    address: "Koregaon Park, Pune",
    contact: "+918200020002",
    locality: "Pune",
    company: "Cognizant",
    emergencyName: "Sonal Deshmukh",
    emergencyContact: "+919888888888",
    emergencyRelation: "Wife",
    createdOn: "17-04-2025",
    name: "Rahul Deshmukh",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "20-04-2025",
    callTag: "Hot",
    staff: "Maya",
    profileImage: "https://randomuser.me/api/portraits/men/18.jpg",
    ptSessions: 0,
  },
  {
    id: 9,
    status: "inactive",
    leadStatus: "lead",
    serviceName: "Membership Plan",
    gender: "female",
    serviceVariation: "6 Month",
    ageGroup: "5-8 years",
    salesRep: "Ravinder",
    memberManager: "Kritika",
    assignedLead: "assigned",
    generalTrainer: "Ravinder",
    leadSource: "Google",
    invoice: "Expired Invoice",
    serviceCategory: "Trial",
    purchaseType: "Events",
    behaviourBased: "Irregular Member",
    fitnessGoal: "Sport",
    customGroups: "Group D",
    enquiryId: 3999609,
    email: "shruti.kapoor@gmail.com",
    dob: "03-09-1992",
    age: "32",
    address: "Anna Nagar, Chennai",
    contact: "+918300030003",
    locality: "Chennai",
    company: "HCL",
    emergencyName: "Rohan Kapoor",
    emergencyContact: "+919000000000",
    emergencyRelation: "Brother",
    createdOn: "16-04-2025",
    name: "Shruti Kapoor",
    leadType: "e-mail", // mockType: e-mail
    enquiryStage: "Enquiry",
    lastUpdated: "19-04-2025",
    callTag: "Cold",
    staff: "Ritika",
    profileImage: "https://randomuser.me/api/portraits/women/26.jpg",
    ptSessions: 1,
  },
  {
    id: 10,
    status: "inactive",
    leadStatus: "new",
    serviceName: "Personal Training",
    gender: "male",
    serviceVariation: "6 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Kritika",
    assignedLead: "assigned",
    generalTrainer: "Kritika",
    leadSource: "Email",
    invoice: "Not Billed Members",
    serviceCategory: "Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Sport",
    customGroups: "Group E",
    enquiryId: 3999610,
    email: "vikram.shah@gmail.com",
    dob: "19-05-1989",
    age: "35",
    address: "Lalbagh Road, Lucknow",
    contact: "+918400040004",
    locality: "Lucknow",
    company: "Tech Mahindra",
    emergencyName: "Anita Shah",
    emergencyContact: "+919111223344",
    emergencyRelation: "Mother",
    createdOn: "15-04-2025",
    name: "Vikram Shah",
    leadType: "walk-in", // mockType: walk-in
    enquiryStage: "Enquiry",
    lastUpdated: "18-04-2025",
    callTag: "Warm",
    staff: "Raj",
    profileImage: "https://randomuser.me/api/portraits/men/19.jpg",
    ptSessions: 0,
  },
];

export const membershipData = [
  {
    title: "Gold Max Membership",
    duration: "3 months",
    features: [
      "Access to certain packages",
      "Priority support",
      "Discount on services",
    ],
    icon: <FaCrown />,
  },
  {
    title: "Silver Flex Membership",
    duration: "1 month",
    features: ["Basic access to services", "No long-term commitment"],
    icon: <FaCrown />,
  },
  {
    title: "Platinum Elite Membership",
    duration: "6 months",
    features: [
      "Full access to premium packages",
      "Free personal trainer sessions",
      "Exclusive invites to events",
    ],
    icon: <FaCrown />,
  },
  {
    title: "Platinum Elite Membership",
    duration: "6 months",
    features: [
      "Full access to premium packages",
      "Free personal trainer sessions",
      "Exclusive invites to events",
    ],
    icon: <FaCrown />,
  },
];

// Dummy lostFoundData for testing
export const lostFoundData = [
  {
    id: 1,
    itemName: "Water Bottle",
    category: "Accessories",
    foundAt: "Locker Room",
    dateTime: "2025-09-18T09:00:00",
    status: "Available",
    loggedBy: "Prashant Dagar",
  },
  {
    id: 2,
    itemName: "Hand Towel",
    category: "Clothing",
    foundAt: "Locker Room",
    dateTime: "2025-09-18T09:00:00",
    status: "Returned",
    loggedBy: "Yogesh Sirohi",
  },
  {
    id: 3,
    itemName: "Sipper",
    category: "Accessories",
    foundAt: "Locker Room",
    dateTime: "2025-09-20T07:30:00",
    status: "Available",
    loggedBy: "Ritika Malhotra",
  },
  {
    id: 4,
    itemName: "Leather Wallet",
    category: "Wallets",
    foundAt: "Locker Room",
    dateTime: "2025-09-21T18:45:00",
    status: "Returned",
    loggedBy: "Amit Verma",
  },
  {
    id: 5,
    itemName: "Towel",
    category: "Clothing",
    foundAt: "Locker Room",
    dateTime: "2025-09-22T08:15:00",
    status: "Available",
    loggedBy: "Sneha Kapoor",
  },
];

// Sales report dummy
export const salesReportData = [
  {
    serialNumber: "01",
    purchaseDate: "03/10/2025",
    billType: "New",
    clubName: "Cybercity",
    memberId: "TL317432",
    memberName: "Shivakar Sharma",
    invoiceNumber: "THR327",
    serviceType: "Membership",
    serviceName: "6 months plan",
    startDate: "18 Sep, 2025",
    endDate: "18 Feb, 2025",
    leadOwner: "Vaibhav Bhardwaj",
    amount: 15000,
    discount: 1000,
    subtotal: 14000,
    cgst: 191.05,
    sgst: 191.05,
    igst: 0,
    finalAmount: 10000000,
    payMode: "UPI",
  },
  {
    serialNumber: "02",
    purchaseDate: "01/10/2025",
    billType: "Renewal",
    clubName: "Cyberhub",
    memberId: "TL317432",
    memberName: "Ashish Choudhary",
    invoiceNumber: "THR327",
    serviceType: "Membership",
    serviceName: "Power Pilates",
    startDate: "18 Sep, 2025",
    endDate: "18 Sep, 2025",
    leadOwner: "Tapan Nayak",
    amount: 1200,
    discount: 100,
    subtotal: 1100,
    cgst: 23.45,
    sgst: 23.45,
    igst: 0,
    finalAmount: 10000000,
    payMode: "Credit Card",
  },
  {
    serialNumber: "03",
    purchaseDate: "01/10/2025",
    billType: "Renewal",
    clubName: "Club 5",
    memberId: "TL317432",
    memberName: "Shashikant Tyagi",
    invoiceNumber: "THR327",
    serviceType: "Package",
    serviceName: "12 months plan",
    startDate: "18 Sep, 2025",
    endDate: "18 Sep, 2026",
    leadOwner: "Prem Kumar",
    amount: 30000,
    discount: 1000,
    subtotal: 29000,
    cgst: 382.1,
    sgst: 382.1,
    igst: 0,
    finalAmount: 1000000,
    payMode: "Credit Card",
  },
  {
    serialNumber: "04",
    purchaseDate: "02/10/2025",
    billType: "New",
    clubName: "Club 4",
    memberId: "TL317432",
    memberName: "Aman Kumar Gupta",
    invoiceNumber: "THR327",
    serviceType: "Package",
    serviceName: "Almond Mocha",
    startDate: "18 Sep, 2025",
    endDate: "18 Oct, 2025",
    leadOwner: "Khushi Singh",
    amount: 250,
    discount: 20,
    subtotal: 230,
    cgst: 5.48,
    sgst: 5.48,
    igst: 0,
    finalAmount: 1000000,
    payMode: "UPI",
  },
  {
    serialNumber: "05",
    purchaseDate: "02/10/2025",
    billType: "New",
    clubName: "Club 4",
    memberId: "TL317432",
    memberName: "Aman Kumar Gupta",
    invoiceNumber: "THR327",
    serviceType: "Product",
    serviceName: "Almond Mocha",
    startDate: "18 Sep, 2025",
    endDate: "18 Oct, 2025",
    leadOwner: "Khushi Singh",
    amount: 250,
    discount: 20,
    subtotal: 230,
    cgst: 5.48,
    sgst: 5.48,
    igst: 0,
    finalAmount: 1000000,
    payMode: "UPI",
  },
  {
    serialNumber: "06",
    purchaseDate: "01/10/2025",
    billType: "Renewal",
    clubName: "Club 5",
    memberId: "TL317432",
    memberName: "Divakar Tyagi",
    invoiceNumber: "THR327",
    serviceType: "Product",
    serviceName: "12 months plan",
    startDate: "18 Sep, 2025",
    endDate: "18 Sep, 2026",
    leadOwner: "Prem Kumar",
    amount: 30000,
    discount: 1000,
    subtotal: 29000,
    cgst: 382.1,
    sgst: 382.1,
    igst: 0,
    finalAmount: 1000000,
    payMode: "Credit Card",
  },
];

// Trial Appointments
export const trialAppointments = [
  {
    enquiryDate: "01/10/2025",
    appointmentCategory: "Complimentary",
    appointmentName: "Trial/Test",
    leadName: "Shivakar Sharma",
    dateTime: "18/09/2025 09:38AM",
    staffName: "Ritu Sharma",
    scheduledBy: "Nitin Sehgal",
    status: "No-Show",
  },
  {
    enquiryDate: "02/10/2025",
    appointmentCategory: "Complimentary",
    appointmentName: "Trial/Test",
    leadName: "Tapan Nayak",
    dateTime: "18/09/2025 09:38AM",
    staffName: "Supriya Sanyal",
    scheduledBy: "Preeti Singh",
    status: "Completed",
  },
  {
    enquiryDate: "29/09/2025",
    appointmentCategory: "Complimentary",
    appointmentName: "Trial/Test",
    leadName: "Anurag Jha",
    dateTime: "18/09/2025 09:38AM",
    staffName: "Preeti Singh",
    scheduledBy: "Anushka Sharma",
    status: "Completed",
  },
  {
    enquiryDate: "30/09/2025",
    appointmentCategory: "Complimentary",
    appointmentName: "Trial/Test",
    leadName: "Aman Rawat",
    dateTime: "18/09/2025 09:38AM",
    staffName: "Sushant Singh",
    scheduledBy: "Samarjeet Singh",
    status: "Scheduled",
  },
];

export const memberCheckInData = [
  {
    serialNumber: 1,
    memberId: "MBR001",
    name: "John Doe",
    serviceName: "Personal Training",
    checkinDate: "05/10/2025",
    location: "Cyberpark",
    clockIn: "08:00 AM",
    clockOut: "09:00 AM",
    conductedBy: "Coach Alex",
  },
  {
    serialNumber: 2,
    memberId: "MBR002",
    name: "Jane Smith",
    serviceName: "Yoga Session",
    checkinDate: "05/10/2025",
    location: "Cyberpark",
    clockIn: "10:00 AM",
    clockOut: "11:00 AM",
    conductedBy: "Instructor Lisa",
  },
  {
    serialNumber: 3,
    memberId: "MBR003",
    name: "Mike Johnson",
    serviceName: "Zumba Class",
    checkinDate: "05/10/2025",
    location: "Cyberpark",
    clockIn: "06:00 PM",
    clockOut: "07:00 PM",
    conductedBy: "Trainer Nina",
  },
];

export const productsSold = [
  {
    serialNumber: 1,
    purchaseDate: "04/10/2025",
    billType: "New Booking",
    clubName: "Cyberpark",
    memberId: "TL317463",
    memberName: "Ankit Sharma",
    serviceType: "Package",
    servicesName: "Personal Training",
    variation: "12-Sessions",
    startDate: "05/10/2025",
    endDate: "09/10/2025",
    leadOwner: "Supriya",
  },
  {
    serialNumber: 2,
    purchaseDate: "03/10/2025",
    billType: "New Booking",
    clubName: "Cyberpark",
    memberId: "TL317464",
    memberName: "Ravi Kumar",
    serviceType: "Package",
    servicesName: "Personal Training",
    variation: "10-Sessions",
    startDate: "06/10/2025",
    endDate: "10/10/2025",
    leadOwner: "Supriya",
  },
  {
    serialNumber: 3,
    purchaseDate: "04/10/2025",
    billType: "Renewal",
    clubName: "Cyberpark",
    memberId: "TL317465",
    memberName: "Priya Mehta",
    serviceType: "Package",
    servicesName: "Personal Training",
    variation: "15-Sessions",
    startDate: "07/10/2025",
    endDate: "11/10/2025",
    leadOwner: "Supriya",
  },
  {
    serialNumber: 4,
    purchaseDate: "05/10/2025",
    billType: "New Booking",
    clubName: "Cyberpark",
    memberId: "TL317466",
    memberName: "Vikram Singh",
    serviceType: "Package",
    servicesName: "Personal Training",
    variation: "8-Sessions",
    startDate: "08/10/2025",
    endDate: "12/10/2025",
    leadOwner: "Supriya",
  },
  {
    serialNumber: 5,
    purchaseDate: "06/10/2025",
    billType: "New Booking",
    clubName: "Cyberpark",
    memberId: "TL317467",
    memberName: "Sanya Gupta",
    serviceType: "Package",
    servicesName: "Personal Training",
    variation: "20-Sessions",
    startDate: "09/10/2025",
    endDate: "13/10/2025",
    leadOwner: "Supriya",
  },
];

export const trainerAvailability = {
  shivakar: [
    { date_time: "2025-11-01T08:00:00.000Z" },
    { date_time: "2025-11-03T10:30:00.000Z" },
    { date_time: "2025-11-07T17:00:00.000Z" },
    { date_time: "2025-11-10T13:00:00.000Z" },
    { date_time: "2025-11-15T03:30:00.000Z" },
    { date_time: "2025-11-20T05:30:00.000Z" },
    { date_time: "2025-11-25T16:00:00.000Z" },
    { date_time: "2025-11-30T08:00:00.000Z" },
  ],
  esha: [
    { date_time: "2025-11-02T09:00:00.000Z" },
    { date_time: "2025-11-06T14:00:00.000Z" },
    { date_time: "2025-11-08T16:00:00.000Z" },
    { date_time: "2025-11-13T12:30:00.000Z" },
    { date_time: "2025-11-17T15:00:00.000Z" },
    { date_time: "2025-11-21T10:00:00.000Z" },
    { date_time: "2025-11-24T11:00:00.000Z" },
    { date_time: "2025-11-29T09:30:00.000Z" },
  ],
  nitin: [
    { date_time: "2025-11-04T10:00:00.000Z" },
    { date_time: "2025-11-10T15:30:00.000Z" },
    { date_time: "2025-11-12T08:30:00.000Z" },
    { date_time: "2025-11-16T14:00:00.000Z" },
    { date_time: "2025-11-19T13:00:00.000Z" },
    { date_time: "2025-11-23T11:00:00.000Z" },
    { date_time: "2025-11-27T09:00:00.000Z" },
    { date_time: "2025-11-30T10:30:00.000Z" },
  ],
};

export const todaySessions = [
  {
    id: 1,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 2,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 3,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 4,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 5,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 6,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 7,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 8,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 9,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 10,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
];

export const servicesList = [
  { value: "membership plan", label: "Membership Plan" },
  { value: "personal training", label: "Personal Training" },
  { value: "thrive membership fee", label: "Thrive Membership Fee" },
  {
    value: "corporate wellness activations",
    label: "Corporate Wellness Activations",
  },
  { value: "miscellaneous fee", label: "Miscellaneous Fee" },
  { value: "nutrition packages", label: "Nutrition Packages" },
];

export const sampleProducts = [
  {
    id: 1,
    productName: "Membership Plan",
    shortDescription: "6 Days Per week. Valid for 6 month(s).",
    servicesDuration: "6 months plan",
    amount: "100",
    sessions: "NA",
    month: 6,
  },
  {
    id: 2,
    productName: "Membership Plan",
    shortDescription: "1 Day Per week. Valid for 12 month(s).",
    servicesDuration: "12 months plan",
    amount: "200",
    sessions: "NA",
    month: 12,
  },
  {
    id: 3,
    productName: "Membership Plan",
    shortDescription: "6 Days Per week. Valid for 13 month(s).	",
    servicesDuration: "12 Months Promotional Plan",
    amount: "300",
    sessions: "NA",
    month: 13,
  },
];

export const productsByType = {
  "membership plan": [
    {
      id: 1,
      productName: "6-Month Membership (6 Days/Week)",
      shortDescription: "6 Days Per week. Valid for 6 month(s).",
      servicesDuration: "6 months plan",
      amount: 100,
      sessions: "NA",
      month: 6,
    },
    {
      id: 2,
      productName: "12-Month Membership (1 Day/Week)",
      shortDescription: "1 Day Per week. Valid for 12 month(s).",
      servicesDuration: "12 months plan",
      amount: 200,
      sessions: "NA",
      month: 12,
    },
    {
      id: 3,
      productName: "13-Month Membership (Promo: 6 Days/Week)",
      shortDescription: "6 Days Per week. Valid for 13 month(s).",
      servicesDuration: "12 Months Promotional Plan",
      amount: 300,
      sessions: "NA",
      month: 13,
    },
  ],

  "personal training": [
    {
      id: 4,
      productName: "10 Session Personal Training Pack",
      shortDescription: "10 Session Pack – 1-on-1 training",
      servicesDuration: "10 sessions plan",
      amount: 500,
      sessions: "NA",
      month: 3,
    },
    {
      id: 5,
      productName: "20 Session Personal Training Pack",
      shortDescription: "20 Session Pack – 1-on-1 training",
      servicesDuration: "20 sessions plan",
      amount: 900,
      sessions: "NA",
      month: 6,
    },
  ],

  "thrive membership fee": [
    {
      id: 6,
      productName: "Thrive Monthly Membership Fee",
      shortDescription: "Thrive Monthly Subscription",
      servicesDuration: "1 month",
      amount: 150,
      sessions: "NA",
      month: 1,
    },
  ],

  "corporate wellness activations": [
    {
      id: 7,
      productName: "Corporate Wellness – One-Time Workshop",
      shortDescription: "One-time corporate workshop session",
      servicesDuration: "1-day event",
      amount: 1200,
      sessions: "NA",
      month: 0,
    },
    {
      id: 8,
      productName: "Corporate Wellness – 3-Month Weekly Sessions",
      shortDescription: "Weekly sessions for 3 months",
      servicesDuration: "12 sessions",
      amount: 3000,
      sessions: "NA",
      month: 3,
    },
  ],

  "miscellaneous fee": [
    {
      id: 9,
      productName: "Monthly Locker Rental",
      shortDescription: "Locker Rental Fee – Monthly",
      servicesDuration: "1 month",
      amount: 50,
      sessions: "NA",
      month: 1,
    },
    {
      id: 10,
      productName: "One-Time Late Payment Fee",
      shortDescription: "Late Payment Fee",
      servicesDuration: "One-time",
      amount: 25,
      sessions: "NA",
      month: 0,
    },
  ],

  "nutrition packages": [
    {
      id: 11,
      productName: "Basic Nutrition Consultation (4 Weeks)",
      shortDescription: "Basic Meal Plan Consultation (4 Weeks)",
      servicesDuration: "1 month",
      amount: "250",
      sessions: "NA",
      month: 1,
    },
    {
      id: 12,
      productName: "3-Month Meal Coaching Program",
      shortDescription: "3-Month Meal Coaching Program",
      servicesDuration: "3 months",
      amount: "700",
      sessions: "NA",
      month: 3,
    },
  ],
};

export const servicesData = [
  {
    id: 1,
    title: "Cricket",
    type: "cricket",
    category: "Sports",
    clubName: "Cricket Club",
    description:
      "Experience the thrill of cricket with our premium pitches, professional-grade equipment, and expert coaching.",
    price: 300,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 2,
    title: "Pickleball",
    type: "pickleball",
    category: "Sports",
    clubName: "Pickleball Club",
    description:
      "Try out one of the fastest growing sports with top-quality pickleball courts and gear.",
    price: 250,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 3,
    title: "Tennis",
    type: "tennis",
    category: "Sports",
    clubName: "Tennis Club",
    description:
      "Play on professionally maintained tennis courts. We offer coaching sessions, match play, and equipment rentals.",
    price: 350,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 4,
    title: "Table Tennis",
    type: "table tennis",
    category: "Sports",
    clubName: "Table Club",
    description:
      "Challenge your reflexes with fast-paced table tennis games in our indoor facilities.",
    price: 150,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 5,
    title: "Football",
    type: "football",
    category: "Sports",
    clubName: "Football Club",
    description:
      "Join our 5-a-side and full-field football matches in high-quality turf arenas.",
    price: 400,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 6,
    title: "Basketball",
    type: "basketball",
    category: "Sports",
    clubName: "Basketball Club",
    description:
      "Shoot hoops at our professional basketball courts with high-quality equipment and flooring.",
    price: 280,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 7,
    title: "Badminton",
    type: "badminton",
    category: "Sports",
    clubName: "Cricket Club",
    description:
      "Play on indoor badminton courts with high-grade shuttlecocks and rackets available.",
    price: 220,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 8,
    title: "Swimming",
    type: "swimming",
    category: "Sports",
    clubName: "Swimming Club",
    description:
      "Enjoy lap swimming or take lessons in our temperature-controlled indoor pool.",
    price: 350,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 9,
    title: "Skating",
    type: "skating",
    category: "Sports",
    clubName: "Skating Club",
    description:
      "Roll into action at our smooth skating rink with rentals and music sessions.",
    price: 180,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 10,
    title: "Yoga",
    type: "yoga",
    trainerName: "Gaurav",
    trainerId: 252,
    category: "GX", // Yoga as part of GX (Group Exercise)
    description:
      "Relax and rejuvenate with guided yoga classes for all levels, including Hatha, Vinyasa, and more.",
    price: 200,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 11,
    title: "Personal Training",
    type: "pt",
    trainerName: "Deepak",
    trainerId: 858,
    category: "Trainers",
    description:
      "Get one-on-one guidance with certified personal trainers for customized fitness plans.",
    price: 500,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 12,
    title: "Strength Coaching",
    type: "nc",
    trainerName: "Leena",
    trainerId: 878,
    category: "Trainers",
    description:
      "Build muscle and strength under the supervision of experienced strength coaches.",
    price: 450,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 13,
    title: "Weight Loss Coach",
    type: "nc",
    trainerName: "Pooja",
    trainerId: 8778,
    category: "Trainers",
    description:
      "Effective fat-loss programs with nutritional tracking and fitness routines.",
    price: 400,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 14,
    title: "Rehabilitation Training",
    type: "spa",
    trainerName: "Omkar",
    trainerId: 8578,
    category: "Trainers",
    description:
      "Injury recovery and mobility support with professional physiotherapy trainers.",
    price: 600,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 15,
    title: "Online Coaching",
    type: "salon",
    trainerName: "Yash",
    trainerId: 8508,
    category: "Trainers",
    description:
      "Remote fitness training sessions via video with personalized feedback.",
    price: 300,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },

  {
    id: 16,
    title: "Zumba",
    type: "zumba",
    trainerName: "Umesh",
    trainerId: 8008,
    category: "GX",
    subCategory: "Group Class",
    description:
      "Dance your way to fitness with fun and energetic Zumba group classes.",
    price: 250,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 17,
    title: "Pilates",
    type: "pilates",
    trainerName: "Tanya",
    trainerId: 8004,
    category: "GX",
    subCategory: "Group Class",
    description:
      "Strengthen your core and improve posture in our group Pilates sessions.",
    price: 300,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 18,
    title: "Dance Event",
    type: "dance",
    trainerName: "Rajesh",
    trainerId: 8104,
    category: "GX",
    subCategory: "Event",
    description:
      "Join our energetic dance event — perfect for fun and fitness.",
    price: 280,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 19,
    title: "Makeup Workshop",
    type: "makeup",
    trainerName: "Esha",
    trainerId: 1459,
    category: "GX",
    subCategory: "Event",
    description: "Learn professional makeup techniques in our weekend events.",
    price: 320,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 20,
    title: "Makeup Workshop",
    type: "makeup",
    trainerName: "Waqar",
    trainerId: 1234,
    category: "GX",
    subCategory: "Event",
    description: "Learn professional makeup techniques in our weekend events.",
    price: 320,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
];

export const slotAvailability = {
  "2025-05-21": {
    "06:00": { status: "booked", service: "Cricket" },
    "08:00": { status: "booked", service: "Tennis" },
    "11:00": { status: "booked", service: "Pickleball" },
    "14:00": { status: "booked", service: "Table-tennis" },
    "18:00": { status: "booked", service: "Tennis" },
  },
  "2025-05-22": {
    "05:00": { status: "booked", service: "Pickleball" },
    "08:00": { status: "booked", service: "Cricket" },
    "10:00": { status: "booked", service: "Tennis" },
    "14:00": { status: "booked", service: "Table-tennis" },
    "18:00": { status: "booked", service: "Pickleball" },
  },
};

export const emailTemplates = {
  welcome: `<div><title></title><meta content="text/html; charset=utf-8"><meta content="width=device-width, initial-scale=1.0"><link><style>*{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}.image_block img+div{display:none}sub,sup{font-size:75%;line-height:0}@media (max-width:720px){.desktop_hide table.icons-inner,.row-12 .column-1 .block-3.button_block .alignment .button,.social_block.desktop_hide .social-table{display:inline-block!important}.icons-inner{text-align:center}.icons-inner td{margin:0 auto}.mobile_hide{display:none}.row-content{width:100%!important}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}.reverse{display:table;width:100%}.reverse .column.first{display:table-footer-group!important}.reverse .column.last{display:table-header-group!important}.row-6 td.column.first .border,.row-6 td.column.last .border{padding:30px}.row-8 td.column.first .border,.row-8 td.column.last .border{padding:0}.row-2 .column-1 .block-2.paragraph_block td.pad>div,.row-8 .column-1 .block-2.heading_block h3{font-size:18px!important}.row-2 .column-1 .block-2.paragraph_block td.pad{padding:6px 10px!important}.row-11 .column-1 .block-1.button_block td.pad,.row-2 .column-1 .block-1.heading_block td.pad,.row-2 .column-1 .block-3.button_block td.pad{padding:10px!important}.row-2 .column-1 .block-1.heading_block h1{font-size:32px!important}.row-11 .column-1 .block-1.button_block span,.row-12 .column-1 .block-3.button_block span,.row-2 .column-1 .block-3.button_block span{line-height:32px!important}.row-5 .column-1 .block-2.heading_block h2,.row-5 .column-2 .block-2.heading_block h2,.row-6 .column-1 .block-2.heading_block h2,.row-6 .column-2 .block-2.heading_block h2{font-size:40px!important}.row-5 .column-1 .block-3.paragraph_block td.pad>div,.row-5 .column-2 .block-3.paragraph_block td.pad>div,.row-6 .column-1 .block-3.paragraph_block td.pad>div,.row-6 .column-2 .block-3.paragraph_block td.pad>div{font-size:16px!important}.row-5 .column-1 .block-3.paragraph_block td.pad,.row-5 .column-2 .block-3.paragraph_block td.pad,.row-6 .column-1 .block-3.paragraph_block td.pad,.row-6 .column-2 .block-3.paragraph_block td.pad{padding:0 5px 0 0!important}.row-8 .column-1 .block-1.heading_block h3{text-align:center!important;font-size:20px!important}.row-8 .column-1 .block-1.heading_block td.pad{padding:0 0 10px!important}.row-10 .column-1 .block-2.heading_block h2,.row-10 .column-2 .block-2.heading_block h2,.row-10 .column-3 .block-2.heading_block h2,.row-12 .column-1 .block-3.button_block .alignment,.row-8 .column-1 .block-2.heading_block h3,.row-8 .column-1 .block-3.paragraph_block td.pad>div{text-align:center!important}.row-10 .column-1 .block-1.image_block .alignment div,.row-10 .column-2 .block-1.image_block .alignment div,.row-10 .column-3 .block-1.image_block .alignment div{margin:0 auto!important}.row-10 .column-1 .block-3.paragraph_block td.pad>div,.row-10 .column-2 .block-3.paragraph_block td.pad>div,.row-10 .column-3 .block-3.paragraph_block td.pad>div{text-align:center!important;font-size:16px!important}.row-10 .column-1,.row-10 .column-1 .block-3.paragraph_block td.pad,.row-10 .column-2,.row-10 .column-2 .block-3.paragraph_block td.pad,.row-10 .column-3 .block-3.paragraph_block td.pad,.row-11 .column-1,.row-2 .column-1,.row-4 .column-1,.row-9 .column-1{padding:0!important}.row-10 .column-1 .block-2.heading_block h2,.row-10 .column-2 .block-2.heading_block h2,.row-10 .column-3 .block-2.heading_block h2{font-size:24px!important}.row-12 .column-1 .block-2.heading_block h2{text-align:center!important;font-size:32px!important}.row-12 .column-1 .block-2.heading_block td.pad{padding:8px!important}.row-13 .column-1 .block-3.paragraph_block td.pad{padding:4px 32px 14px!important}.row-2 .row-content{padding:22px!important}.row-4 .row-content,.row-9 .row-content{padding:32px 40px 0!important}.row-10 .row-content,.row-5 .row-content{padding:32px 32px 0!important}.row-11 .row-content,.row-6 .row-content{padding:20px 32px 32px!important}.row-12 .row-content,.row-13 .row-content,.row-8 .row-content{padding:32px!important}.row-5 .column-1,.row-5 .column-2,.row-6 .column-1 .border,.row-6 .column-2 .border{padding:24px!important}}</style><table style=mso-table-lspace:0;mso-table-rspace:0;background-color:#fff width=100% border=0 cellpadding=0 cellspacing=0 class=nl-container><tr><td style=border-color:#fff><table style=mso-table-lspace:0;mso-table-rspace:0;margin:0 width=100% border=0 cellpadding=0 cellspacing=0 class="row row-1"align=center><tr><td style=border-color:#fff;padding:0><table style="mso-table-lspace:0;mso-table-rspace:0;background-color:#0c3c36;color:#000;width:700px;margin:0 auto"width=700 border=0 cellpadding=0 cellspacing=0 class="row-content stack"align=center><tr><td style=mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top class="column column-1"width=100%><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="block-1 image_block"><tr><td style=padding-bottom:10px;padding-top:20px;width:100%;border-color:#0c3c36 class=pad><div class=alignment><div style=max-width:169px><a href=https://www.example.com/ target=_blank><img alt="Charity Logo Placeholder"height=48 src=https://d1oco4z2z1fhwp.cloudfront.net/templates/default/10536/BrightPath_Logo.png style=display:block;height:auto;border:0;width:100% width=169 title="Charity Logo Placeholder"></a></div></div></table></table></table><table style=mso-table-lspace:0;mso-table-rspace:0;margin:0 width=100% border=0 cellpadding=0 cellspacing=0 class="row row-2"align=center><tr><td style=border-color:#fff;padding:0><table style="mso-table-lspace:0;mso-table-rspace:0;background-color:#faf9f6;border-radius:0;color:#000;padding:60px;width:700px;margin:0 auto"width=700 border=0 cellpadding=0 cellspacing=0 class="row-content stack"align=center><tr><td style="font-weight:400;text-align:left;padding-left:60px;padding-right:60px;vertical-align:top;border-color:rgb(250 249 246);border:none!important"class="column column-1"width=100%><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="block-1 heading_block"><tr><td style="padding:4px 10px 14px;text-align:center;width:100%;border-color:#faf9f6"class=pad><h1 style="margin:0;color:#0c3c36;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:64px;font-weight:700;letter-spacing:-2px;line-height:1;text-align:center;margin-top:0;margin-bottom:0;mso-line-height-alt:64px"><span style=word-break:break-word class=tinyMce-placeholder>Small Actions.<br>Big Impact.</span></h1></table><table style=mso-table-lspace:0;mso-table-rspace:0;word-break:break-word width=100% border=0 cellpadding=10 cellspacing=0 class="block-2 paragraph_block"><tr><td style=border-color:#faf9f6 class=pad><div style="color:#0c3c36;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:20px;font-weight:400;letter-spacing:-1px;line-height:1.2;text-align:center;mso-line-height-alt:24px"><p style=margin:0>This Giving Tuesday, your support can help plant trees, restore habitats, and inspire the next generation to protect our planet.</div></table><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="block-3 button_block"><tr><td style="padding:10px 10px 4px;text-align:center;border-color:#faf9f6"class=pad><div class=alignment><a href=https://www.example.com/ target=_blank style=color:#faf9f6;text-decoration:none><span style="background-color:#427761;mso-shading:transparent;border-bottom:0 solid transparent;border-left:0 solid transparent;border-radius:8px;border-right:0 solid transparent;border-top:0 solid transparent;color:#faf9f6;display:inline-block;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:16px;font-weight:500;mso-border-alt:none;padding-bottom:5px;padding-top:5px;padding-left:24px;padding-right:24px;text-align:center;width:auto;word-break:keep-all;letter-spacing:normal"class=button><span style=word-break:break-word;line-height:32px>Join the Movement</span></span></a></div></table></table></table><table style=mso-table-lspace:0;mso-table-rspace:0;margin:0 width=100% border=0 cellpadding=0 cellspacing=0 class="row row-3"align=center><tr><td style=border-color:#fff;padding:0><table style="mso-table-lspace:0;mso-table-rspace:0;background-color:#faf9f6;border-radius:0;color:#000;width:700px;margin:0 auto"width=700 border=0 cellpadding=0 cellspacing=0 class="row-content stack"align=center><tr><td style=font-weight:400;text-align:left;vertical-align:top;border-color:#faf9f6;padding:0;border:none!important class="column column-1"width=100%><table style=mso-table-lspace:0;mso-table-rspace:0;margin:0;padding:0;border:none!important width=100% border=0 cellpadding=0 cellspacing=0 class="block-1 image_block"><tr><td style=width:100%;padding:0;border:none!important class=pad><div class=alignment><div style=max-width:700px><img alt="a group of people hugging on a hill"height=532 src=https://d1oco4z2z1fhwp.cloudfront.net/templates/default/10536/Hero_Image.png style=display:block;height:auto;border:0;width:100% width=700 title="a group of people hugging on a hill"></div></div></table></table></table><table style=mso-table-lspace:0;mso-table-rspace:0;margin:0 width=100% border=0 cellpadding=0 cellspacing=0 class="row row-4"align=center><tr><td style=padding:0;border:none!important><table style="mso-table-lspace:0;mso-table-rspace:0;padding-left:60px;padding-right:60px;background-color:#e4f0e8;border-radius:0;color:#000;padding-top:52px;width:700px;margin:0 auto"width=700 border=0 cellpadding=0 cellspacing=0 class="row-content stack"align=center><tr><td style=font-weight:400;text-align:left;vertical-align:top;border-color:#e4f0e8 class="column column-1"width=100%><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="block-1 heading_block"><tr><td style=text-align:center;width:100%;border-color:#e4f0e8 class=pad><h3 style="margin:0;color:#0c3c36;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:24px;font-weight:700;letter-spacing:-1px;line-height:1.2;text-align:center;margin-top:0;margin-bottom:0;mso-line-height-alt:29px"><span style=word-break:break-word class=tinyMce-placeholder>Together, we’re making a difference.</span></h3></table></table></table><table style="mso-table-lspace:0;mso-table-rspace:0;margin:0;width:700px!important;margin:0 auto;padding:100px"width=100% border=0 cellpadding=0 cellspacing=0 class="row row-5"align=center><tr><td style=border-color:#fff;padding:50px;border:none!important;background:#e4f0e8><table style=mso-table-lspace:0;mso-table-rspace:0;background-color:#e4f0e8;border-radius:0;margin:0;width:100% width=700 border=0 cellpadding=0 cellspacing=0 class="row-content stack"align=center><tr><td style=font-weight:400;text-align:left;background-color:#2e7155;padding:30px;vertical-align:top;border-radius:16px;border-color:#e4f0e8 class="column column-1"width=50%><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="block-1 image_block"><tr><td style=width:100%;padding:0;border:none!important class=pad><div class=alignment><div style=max-width:86px><img alt="a star on a green background"height=88 src=https://d1oco4z2z1fhwp.cloudfront.net/templates/default/10536/Icon_Star.png style=display:block;height:auto;border:0;width:100% width=86 title="a star on a green background"></div></div></table><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="heading_block block-2"><tr><td style=padding-bottom:4px;padding-top:18px;text-align:center;width:100%;padding:0;border:none!important class=pad><h2 style="margin:0;color:#e4f0e8;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:48px;font-weight:700;letter-spacing:normal;line-height:1.2;text-align:left;margin-top:0;margin-bottom:0;mso-line-height-alt:58px"><span style=word-break:break-word class=tinyMce-placeholder>50+</span></h2></table><table style=mso-table-lspace:0;mso-table-rspace:0;word-break:break-word width=100% border=0 cellpadding=0 cellspacing=0 class="block-3 paragraph_block"><tr><td style=padding-right:45px;padding:0;border:none!important class=pad><div style="color:#e4f0e8;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:20px;font-weight:500;letter-spacing:0;line-height:1.2;text-align:left;mso-line-height-alt:24px"><p style=margin:0>partnerships with local schools</div></table><td style=font-weight:400;text-align:left;vertical-align:top;border-color:#e4f0e8;padding:0;border:none!important class="column gap"><table style=mso-table-lspace:0;mso-table-rspace:0;width:20px;height:20px width=20></table><td style=font-weight:400;text-align:left;background-color:#0c3c36;padding:30px;vertical-align:top;border-radius:16px;border-color:#e4f0e8 class="column column-2"width=50%><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="block-1 image_block"><tr><td style=width:100%;padding:0;border:none!important class=pad><div class=alignment><div style=max-width:96px><img alt="a heart on a green background"height=88 src=https://d1oco4z2z1fhwp.cloudfront.net/templates/default/10536/Icon_Heart.png style=display:block;height:auto;border:0;width:100% width=96 title="a heart on a green background"></div></div></table><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="heading_block block-2"><tr><td style=padding-bottom:4px;padding-top:18px;text-align:center;width:100%;padding:0;border:none!important class=pad><h2 style="margin:0;color:#e4f0e8;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:48px;font-weight:700;letter-spacing:normal;line-height:1.2;text-align:left;margin-top:0;margin-bottom:0;mso-line-height-alt:58px"><span style=word-break:break-word class=tinyMce-placeholder>300</span></h2></table><table style=mso-table-lspace:0;mso-table-rspace:0;word-break:break-word width=100% border=0 cellpadding=0 cellspacing=0 class="block-3 paragraph_block"><tr><td style=padding-right:45px;padding:0;border:none!important class=pad><div style="color:#e4f0e8;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:20px;font-weight:500;letter-spacing:0;line-height:1.2;text-align:left;mso-line-height-alt:24px"><p style=margin:0>communities reached</div></table></table></table><table style="mso-table-lspace:0;mso-table-rspace:0;width:700px!important;margin:0 auto;padding:100px"width=100% border=0 cellpadding=0 cellspacing=0 class="row row-6"align=center><tr><td style=border-color:#fff;padding:50px;border:none!important;background:#e4f0e8;padding-top:0><table style="mso-table-lspace:0;mso-table-rspace:0;background-color:#e4f0e8;border-radius:0;color:#000;width:100%;margin:0 auto"width=700 border=0 cellpadding=0 cellspacing=0 class="row-content stack"align=center><tr class=reverse><td style=mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#0c3c36;padding-bottom:30px;padding-left:30px;padding-right:30px;padding-top:30px;vertical-align:top;border-radius:16px;border:none!important class="column column-1 first"width=50%><div style=padding:0;border:none!important class=border><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="block-1 image_block"><tr><td style=width:100%;padding:0;border:none!important class=pad><div class=alignment><div style=max-width:88px><img alt="a rocket with a green background"height=89 src=https://d1oco4z2z1fhwp.cloudfront.net/templates/default/10536/Icon_Rocket.png style=display:block;height:auto;border:0;width:100% width=88 title="a rocket with a green background"></div></div></table><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="heading_block block-2"><tr><td style=padding-bottom:4px;padding-top:18px;text-align:center;width:100%;padding:0;border:none!important class=pad><h2 style="margin:0;color:#e4f0e8;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:48px;font-weight:700;letter-spacing:normal;line-height:1.2;text-align:left;margin-top:0;margin-bottom:0;mso-line-height-alt:58px"><span style=word-break:break-word class=tinyMce-placeholder>1,400</span></h2></table><table style=mso-table-lspace:0;mso-table-rspace:0;word-break:break-word width=100% border=0 cellpadding=0 cellspacing=0 class="block-3 paragraph_block"><tr><td style=padding-right:45px;padding:0;border:none!important class=pad><div style="color:#e4f0e8;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:20px;font-weight:500;letter-spacing:0;line-height:1.2;text-align:left;mso-line-height-alt:24px"><p style=margin:0>volunteers in action</div></table></div><td style=mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding:0;border:none!important class="column gap"><table style=mso-table-lspace:0;mso-table-rspace:0;width:20px;height:20px width=20></table><td style=mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#2e7155;padding-bottom:30px;padding-left:30px;padding-right:30px;padding-top:30px;vertical-align:top;border-radius:16px;border:none!important class="column column-2 last"width=50%><div style=padding:0;border:none!important class=border><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="block-1 image_block"><tr><td style=width:100%;padding:0;border:none!important class=pad><div class=alignment><div style=max-width:95px><img alt="a globe with a green background"height=88 src=https://d1oco4z2z1fhwp.cloudfront.net/templates/default/10536/Icon_Globe.png style=display:block;height:auto;border:0;width:100% width=95 title="a globe with a green background"></div></div></table><table style=mso-table-lspace:0;mso-table-rspace:0 width=100% border=0 cellpadding=0 cellspacing=0 class="heading_block block-2"><tr><td style=padding-bottom:4px;padding-top:18px;text-align:center;width:100%;padding:0;border:none!important class=pad><h2 style="margin:0;color:#e4f0e8;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:48px;font-weight:700;letter-spacing:normal;line-height:1.2;text-align:left;margin-top:0;margin-bottom:0;mso-line-height-alt:58px"><span style=word-break:break-word class=tinyMce-placeholder>3.8</span></h2></table><table style=mso-table-lspace:0;mso-table-rspace:0;word-break:break-word width=100% border=0 cellpadding=0 cellspacing=0 class="block-3 paragraph_block"><tr><td style=padding-right:15px;padding:0;border:none!important class=pad><div style="color:#e4f0e8;direction:ltr;font-family:'Plus Jakarta Sans',Helvetica,Poppins;font-size:20px;font-weight:500;letter-spacing:0;line-height:1.2;text-align:left;mso-line-height-alt:24px"><p style=margin:0>tons of waste collected</div></table></div></table></table><table style=mso-table-lspace:0;mso-table-rspace:0;margin:0 width=100% border=0 cellpadding=0 cellspacing=0 class="row mobile_hide row-7"align=center><tr><td style=padding:0;border:none!important><table style="mso-table-lspace:0;mso-table-rspace:0;background-color:#e4f0e8;border-radius:0;color:#000;width:700px;margin:0 auto"width=700 border=0 cellpadding=0 cellspacing=0 class="row-content stack"align=center><tr><td style=mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding:0;border:none!important class="column column-1"width=100%><div style=height:20px;line-height:20px;font-size:1px class="block-1 spacer_block"> </div></table></table><table style=mso-table-lspace:0;mso-table-rspace:0;background-color:#fff width=100% border=0 cellpadding=0 cellspacing=0 class="row row-14"align=center><tr><td style=padding:0;border:none!important><table style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:700px;margin:0 auto"width=700 border=0 cellpadding=0 cellspacing=0 class="row-content stack"align=center><tr><td style=mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-top:5px;vertical-align:top;padding:0;border:none!important class="column column-1"width=100%><table style=mso-table-lspace:0;mso-table-rspace:0;text-align:center;line-height:0 width=100% border=0 cellpadding=0 cellspacing=0 class="block-1 icons_block"><tr><td style=vertical-align:middle;color:#1e0e4b;font-family:Inter,sans-serif;font-size:15px;padding-bottom:5px;padding-top:5px;text-align:center;padding:0;border:none!important class=pad><table style=mso-table-lspace:0;mso-table-rspace:0;display:inline-block;padding-left:0;padding-right:0;margin:0 cellpadding=0 cellspacing=0 class=icons-inner><tr><td style=vertical-align:middle;text-align:center;padding-top:5px;padding-bottom:5px;padding-left:5px;padding-right:6px;border:none!important><a href=https://designedwithbeefree.com/ target=_blank style=text-decoration:none title="Designed with Beefree"><img alt="Beefree Logo"height=32 src=https://d1oco4z2z1fhwp.cloudfront.net/assets/Beefree-logo.png style="display:block;height:auto;margin:0 auto;border:0"width=34 align=center class=icon></a><td style="font-family:Inter,sans-serif;font-size:15px;font-weight:undefined;color:#1e0e4b;vertical-align:middle;letter-spacing:normal;text-align:center;line-height:normal;border:none!important"><a href=https://designedwithbeefree.com/ target=_blank style=color:#1e0e4b;text-decoration:none title="Designed with Beefree">Designed with Beefree</a></table></table></table></table></table></div>`,
  renewal: `
    <h2>Your Membership is Expiring Soon</h2>
    <p>This is a reminder that your membership is due for renewal.</p>
    <p>Renew now to continue enjoying uninterrupted services.</p>
  `,
  promotion: `
    <h2>Special Offer Just for You!</h2>
    <p>Get <strong>30% OFF</strong> on select services this month.</p>
    <p>Don't miss out on this exclusive deal!</p>
  `,
};

export const smsTemplates = {
  renewal:
    "Your membership is expiring soon. This is a reminder that your membership is due for renewal. Renew now to continue enjoying uninterrupted services.",
  promotion:
    "Special offer just for you! Get 30% OFF on select services this month. Don't miss out on this exclusive deal!",
  welcome:
    "Welcome aboard! Thank you for joining our community. We are excited to have you with us!",
  passwordReset:
    "Password reset request received. Click the link below to reset your password safely.",
  appointmentReminder:
    "Reminder: You have an upcoming appointment. Please arrive 10 minutes early.",
};
