import { FaCrown } from "react-icons/fa";

export const followUpsData = [
  {
    id: 1,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 2,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Attempted",
    type: "enquiry calls",
  },
  {
    id: 3,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Contacted",
    type: "welcome calls",
  },
  {
    id: 4,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 5,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 6,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
];

export const assignedLeadsData = [
  {
    id: 1,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 2,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Attempted",
    type: "enquiry calls",
  },
  {
    id: 3,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Contacted",
    type: "welcome calls",
  },
  {
    id: 4,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 5,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
  {
    id: 6,
    name: "Rohan Bakshi",
    contact: "8756556***",
    tag: "Membership Plan",
    status: "Scheduled",
    type: "enquiry calls",
  },
];

export const trialScheduledUsers = [
  {
    id: 1,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 2,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 3,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
];

export const leadsStatus = {
  chart: {
    type: "column",
    height: 300,
  },
  title: {
    text: "Leads Distribution by Status",
    align: "left",
    style: {
      fontSize: "16px",
      fontWeight: "600",
    },
  },
  xAxis: {
    categories: ["New", "Contacted", "Lost", "Trial Scheduled"],
    title: {
      text: null,
    },
    labels: {
      style: {
        fontSize: "10px",
      },
    },
  },
  yAxis: {
    min: 0,
    title: {
      text: null,
    },
    gridLineColor: "#e5e5e5",
  },
  legend: {
    enabled: false,
  },
  tooltip: {
    pointFormat: "Count: <b>{point.y}</b>",
  },
  plotOptions: {
    column: {
      borderRadius: 3,
      pointPadding: 0.2,
      borderWidth: 0,
      color: "#888888",
    },
  },
  series: [
    {
      name: "Leads",
      data: [75, 40, 60, 45],
    },
  ],
  credits: {
    enabled: false,
  },
};

export const groupClasses = {
  chart: {
    type: "column",
    height: 400,
  },
  title: {
    text: "Group Classes Statistics",
    align: "left",
    style: {
      fontSize: "16px",
      fontWeight: "600",
    },
  },
  credits: {
    enabled: false,
  },
  xAxis: {
    categories: ["1 Apr", "2 Apr", "3 Apr", "4 Apr", "5 Apr", "6 Apr", "7 Apr"],
    title: { text: null },
  },
  yAxis: {
    min: 0,
    title: {
      text: null,
    },
    stackLabels: {
      enabled: false,
      style: {
        fontWeight: "bold",
        color: "red",
      },
    },
  },
  legend: {
    align: "right",
    verticalAlign: "top",
    layout: "horizontal",
    symbolRadius: 6,
    itemStyle: {
      fontWeight: "normal",
      fontSize: "13px",
    },
    labelFormatter: function () {
      const colors = {
        Cancellations: "#6b6b6b",
        Reservations: "#bcbcbc",
        Bookings: "#e0e0e0",
      };
      return `<span style="color: ${colors[this.name]}">${this.name}</span>`;
    },
    useHTML: true,
  },
  tooltip: {
    shared: true,
    pointFormat:
      '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b><br/>',
  },
  plotOptions: {
    column: {
      stacking: "normal",
      dataLabels: {
        enabled: false,
      },
    },
  },
  series: [
    {
      name: "Cancellations",
      data: [20, 10, 25, 10, 10, 15, 15],
      color: "#6b6b6b",
    },
    {
      name: "Reservations",
      data: [15, 10, 20, 15, 15, 20, 20],
      color: "#bcbcbc",
    },
    {
      name: "Bookings",
      data: [5, 10, 20, 10, 10, 15, 15],
      color: "#e0e0e0",
    },
  ],
};

export const servicesName = [
  { value: "membership plan", label: "Membership Plan" },
  { value: "personal training", label: "Personal Training" },
  { value: "thrive membership fee", label: "Thrive Membership Fee" },
  { value: "miscellaneous fee", label: "Miscellaneous Fee" },
  { value: "nutrition packages", label: "Nutrition Packages" },
  { value: "event", label: "Event" },
];

export const leadsSources = [
  { value: "corporate", label: "Corporate" },
  { value: "corporate-voucher", label: "Corporate voucher" },
  { value: "events", label: "Events" },
  { value: "facebook", label: "Facebook" },
  { value: "google", label: "Google" },
  { value: "hoardings", label: "Hoardings" },
  { value: "instagram", label: "Instagram" },
  { value: "member-app", label: "Member App" },
  { value: "others", label: "Others" },
  { value: "passing-by", label: "Passing By" },
  { value: "ppc", label: "PPC" },
  { value: "qr", label: "QR" },
  { value: "referral", label: "Referral" },
  { value: "social-media", label: "Social media" },
  { value: "website", label: "Website" },
  { value: "whatsapp", label: "WhatsApp" },
  { value: "word-of-mouth", label: "Word of mouth" },
  { value: "yoactiv", label: "Yoactiv" },
];

export const leadTypes = [
  { value: "walk-in", label: "Walk-in" },
  { value: "phone", label: "Phone" },
  { value: "email", label: "e-mail" },
  { value: "social-media", label: "Social media" },
  { value: "website", label: "Website" },
];

export const companies = [
  { value: "ba-continuum-india-pvt-ltd", label: "BA CONTINUUM INDIA PVT LTD" },
  {
    value: "masters-union-shanti-informatics",
    label: "MASTERS UNION-SHANTI INFORMATICS",
  },
  {
    value: "wpp-marketing-communications-india-p-ltd",
    label: "WPP MARKETING COMMUNICATIONS INDIA P LTD",
  },
  {
    value: "simpliwork-offices-private-limited-arcesium",
    label: "SIMPLIWORK OFFICES PRIVATE LIMITED (ARCESIUM)",
  },
  {
    value: "ey-global-delivery-services-india-llp",
    label: "EY GLOBAL DELIVERY SERVICES INDIA LLP",
  },
  {
    value: "reckitt-benckiser-india-private-ltd",
    label: "RECKITT BENCKISER (INDIA) PRIVATE LTD",
  },
  {
    value: "expedia-online-travel-services-i-p-ltd",
    label: "EXPEDIA ONLINE TRAVEL SERVICES(I) P LTD",
  },
  { value: "campus-active-pvt-ltd", label: "Campus Active Pvt Ltd" },
  { value: "jll", label: "JLL" },
  {
    value: "aviva-life-insurance-company-india-ltd",
    label: "AVIVA LIFE INSURANCE COMPANY INDIA LTD",
  },
  { value: "trilegal", label: "TRILEGAL" },
  { value: "siemens-limited", label: "SIEMENS LIMITED" },
  {
    value: "the-boston-consulting-group-i-pvt-ltd",
    label: "THE BOSTON CONSULTING GROUP (I) PVT LTD",
  },
  { value: "pernod-ricard-india-p-ltd", label: "PERNOD RICARD INDIA (P) LTD." },
  {
    value: "gartner-india-research-advisory-services-pr",
    label: "GARTNER INDIA RESEARCH & ADVISORY SERVICES PR",
  },
  { value: "nab", label: "NAB" },
  {
    value: "agoda-international-india-private-ltd",
    label: "AGODA INTERNATIONAL INDIA PRIVATE LTD.",
  },
  { value: "dr-morepen-limited", label: "DR MOREPEN LIMITED" },
  {
    value: "ipm-india-wholesale-trading-private-limited",
    label: "IPM INDIA WHOLESALE TRADING PRIVATE LIMTED",
  },
  { value: "morepen-laboratories-ltd", label: "MOREPEN LABORATORIES LTD" },
  { value: "volvo-auto-india-pvt-ltd", label: "VOLVO AUTO INDIA PVT . LTD" },
  {
    value: "samsung-india-electronics-private-ltd",
    label: "SAMSUNG INDIA ELECTRONICS PRIVATE LTD",
  },
  { value: "apple-india-pvt-ltd", label: "APPLE INDIA PVT. LTD." },
  { value: "hdfc", label: "HDFC" },
  {
    value: "petrofac-engg-services-india-pvt-ltd",
    label: "Petrofac Engg Services India Pvt Ltd",
  },
];

export const mockData = [
  {
    id: 1,
    status: "Active",
    service: "Membership Plan",
    gender: "male",
    serviceVariation: "1 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Kritika",
    generalTrainer: "Ravinder",
    leadSource: "Google",
    invoice: "Not Billed Members",
    serviceCategory: "Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Sport",
    customGroups: "Group A",
    enquiryId: 3999601,
    email: "janani.singh@gmail.com",
    dob: "01-01-1990",
    age: "34",
    address: "DLF Phase 3, Gurgaon",
    contact: "+918700704309",
    locality: "gurgaon",
    company: "Google India",
    emergencyName: "Aarav Singh",
    emergencyContact: "+919111111111",
    emergencyRelation: "Brother",
    createdOn: "20-04-2025",
    name: "Janani Singh",
    leadType: "phone", // mockType: phone
    enquiryStage: "Enquiry",
    lastUpdated: "24-04-2025",
    callTag: "Hot",
    staff: "Preeti",
    profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 2,
    status: "Inactive",
    service: "Personal Training",
    gender: "female",
    serviceVariation: "6 Month",
    ageGroup: "5-8 years",
    salesRep: "Ravinder",
    memberManager: "Ravinder",
    generalTrainer: "Kritika",
    leadSource: "Email",
    invoice: "Expired Invoice",
    serviceCategory: "PT Trial",
    purchaseType: "Events",
    behaviourBased: "Irregular Member",
    fitnessGoal: "Fat Loss",
    customGroups: "Group B",
    enquiryId: 3999602,
    email: "iftekhar.khan@gmail.com",
    dob: "14-02-1988",
    age: "37",
    address: "Sector 45, Noida",
    contact: "+918234567890",
    locality: "Noida",
    company: "Infosys",
    emergencyName: "Nida Khan",
    emergencyContact: "+919222222222",
    emergencyRelation: "Wife",
    createdOn: "21-04-2025",
    name: "Iftekhar Khan",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "25-04-2025",
    callTag: "Warm",
    staff: "Prerna",
    profileImage: "https://randomuser.me/api/portraits/men/31.jpg",
  },
  {
    id: 3,
    status: "Active",
    service: "Personal Training",
    gender: "Not Specified",
    serviceVariation: "1 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Ravinder",
    generalTrainer: "Kritika",
    leadSource: "Corporate",
    invoice: "Not Billed Members",
    serviceCategory: "PT Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Fat Loss",
    customGroups: "Group C",
    enquiryId: 3999603,
    email: "megha.patel@example.com",
    dob: "05-07-1993",
    age: "31",
    address: "MG Road, Bengaluru",
    contact: "+918765432109",
    locality: "Bengaluru",
    company: "Flipkart",
    emergencyName: "Ravi Patel",
    emergencyContact: "+919333333333",
    emergencyRelation: "Husband",
    createdOn: "22-04-2025",
    name: "Megha Patel",
    leadType: "website", // mockType: website
    enquiryStage: "Enquiry",
    lastUpdated: "26-04-2025",
    callTag: "Cold",
    staff: "Anuj",
    profileImage: "https://randomuser.me/api/portraits/women/32.jpg",
  },
  {
    id: 4,
    status: "Active",
    service: "Membership Plan",
    gender: "female",
    serviceVariation: "6 Month",
    ageGroup: "5-8 years",
    salesRep: "Ravinder",
    memberManager: "Kritika",
    generalTrainer: "Ravinder",
    leadSource: "Google",
    invoice: "Expired Invoice",
    serviceCategory: "Trial",
    purchaseType: "Events",
    behaviourBased: "Irregular Member",
    fitnessGoal: "Sport",
    customGroups: "Group D",
    enquiryId: 3999604,
    email: "rohan.mehta@gmail.com",
    dob: "30-10-1990",
    age: "34",
    address: "Bandra West, Mumbai",
    contact: "+918888880000",
    locality: "Mumbai",
    company: "Tata Consultancy",
    emergencyName: "Neha Mehta",
    emergencyContact: "+919444444444",
    emergencyRelation: "Wife",
    createdOn: "23-04-2025",
    name: "Rohan Mehta",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "27-04-2025",
    callTag: "Hot",
    staff: "Ritika",
    profileImage: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    id: 5,
    status: "Active",
    service: "Membership Plan",
    gender: "male",
    serviceVariation: "6 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Kritika",
    generalTrainer: "Kritika",
    leadSource: "Email",
    invoice: "Not Billed Members",
    serviceCategory: "Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Sport",
    customGroups: "Group E",
    enquiryId: 3999605,
    email: "sneha.jain@yahoo.com",
    dob: "12-03-1996",
    age: "29",
    address: "South Ex, Delhi",
    contact: "+917777777777",
    locality: "New Delhi",
    company: "Zomato",
    emergencyName: "Priya Jain",
    emergencyContact: "+919555555555",
    emergencyRelation: "Sister",
    createdOn: "24-04-2025",
    name: "Sneha Jain",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "28-04-2025",
    callTag: "Warm",
    staff: "Manish",
    profileImage: "https://randomuser.me/api/portraits/women/28.jpg",
  },
  {
    id: 6,
    status: "Active",
    service: "Membership Plan",
    gender: "male",
    serviceVariation: "1 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Kritika",
    generalTrainer: "Ravinder",
    leadSource: "Google",
    invoice: "Not Billed Members",
    serviceCategory: "Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Sport",
    customGroups: "Group A",
    enquiryId: 3999606,
    email: "akash.verma@hotmail.com",
    dob: "22-11-1991",
    age: "33",
    address: "Park Street, Kolkata",
    contact: "+919999999999",
    locality: "Kolkata",
    company: "Wipro",
    emergencyName: "Ritika Verma",
    emergencyContact: "+919666666666",
    emergencyRelation: "Sister",
    createdOn: "19-04-2025",
    name: "Akash Verma",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "23-04-2025",
    callTag: "Cold",
    staff: "Prerna",
    profileImage: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: 7,
    status: "Active",
    service: "Personal Training",
    gender: "female",
    serviceVariation: "6 Month",
    ageGroup: "5-8 years",
    salesRep: "Ravinder",
    memberManager: "Ravinder",
    generalTrainer: "Kritika",
    leadSource: "Email",
    invoice: "Expired Invoice",
    serviceCategory: "PT Trial",
    purchaseType: "Events",
    behaviourBased: "Irregular Member",
    fitnessGoal: "Fat Loss",
    customGroups: "Group B",
    enquiryId: 3999607,
    email: "nisha.rajan@gmail.com",
    dob: "09-06-1994",
    age: "30",
    address: "Vashi, Navi Mumbai",
    contact: "+918100010001",
    locality: "Navi Mumbai",
    company: "Amazon India",
    emergencyName: "Kavya Rajan",
    emergencyContact: "+919777777777",
    emergencyRelation: "Mother",
    createdOn: "18-04-2025",
    name: "Nisha Rajan",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "21-04-2025",
    callTag: "Warm",
    staff: "Alok",
    profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 8,
    status: "Inactive",
    service: "Personal Training",
    gender: "female",
    serviceVariation: "6 Month",
    ageGroup: "5-8 years",
    salesRep: "Ravinder",
    memberManager: "Ravinder",
    generalTrainer: "Kritika",
    leadSource: "Email",
    invoice: "Expired Invoice",
    serviceCategory: "PT Trial",
    purchaseType: "Events",
    behaviourBased: "Irregular Member",
    fitnessGoal: "Fat Loss",
    customGroups: "Group B",
    enquiryId: 3999608,
    email: "rahul.deshmukh@outlook.com",
    dob: "25-12-1985",
    age: "39",
    address: "Koregaon Park, Pune",
    contact: "+918200020002",
    locality: "Pune",
    company: "Cognizant",
    emergencyName: "Sonal Deshmukh",
    emergencyContact: "+919888888888",
    emergencyRelation: "Wife",
    createdOn: "17-04-2025",
    name: "Rahul Deshmukh",
    leadType: "social-media", // mockType: social-media
    enquiryStage: "Enquiry",
    lastUpdated: "20-04-2025",
    callTag: "Hot",
    staff: "Maya",
    profileImage: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: 9,
    status: "Inactive",
    service: "Membership Plan",
    gender: "female",
    serviceVariation: "6 Month",
    ageGroup: "5-8 years",
    salesRep: "Ravinder",
    memberManager: "Kritika",
    generalTrainer: "Ravinder",
    leadSource: "Google",
    invoice: "Expired Invoice",
    serviceCategory: "Trial",
    purchaseType: "Events",
    behaviourBased: "Irregular Member",
    fitnessGoal: "Sport",
    customGroups: "Group D",
    enquiryId: 3999609,
    email: "shruti.kapoor@gmail.com",
    dob: "03-09-1992",
    age: "32",
    address: "Anna Nagar, Chennai",
    contact: "+918300030003",
    locality: "Chennai",
    company: "HCL",
    emergencyName: "Rohan Kapoor",
    emergencyContact: "+919000000000",
    emergencyRelation: "Brother",
    createdOn: "16-04-2025",
    name: "Shruti Kapoor",
    leadType: "e-mail", // mockType: e-mail
    enquiryStage: "Enquiry",
    lastUpdated: "19-04-2025",
    callTag: "Cold",
    staff: "Ritika",
    profileImage: "https://randomuser.me/api/portraits/women/26.jpg",
  },
  {
    id: 10,
    status: "Inactive",
    service: "Personal Training",
    gender: "male",
    serviceVariation: "6 Month",
    ageGroup: "0-5 years",
    salesRep: "Kritika",
    memberManager: "Kritika",
    generalTrainer: "Kritika",
    leadSource: "Email",
    invoice: "Not Billed Members",
    serviceCategory: "Trial",
    purchaseType: "Membership",
    behaviourBased: "Referrers",
    fitnessGoal: "Sport",
    customGroups: "Group E",
    enquiryId: 3999610,
    email: "vikram.shah@gmail.com",
    dob: "19-05-1989",
    age: "35",
    address: "Lalbagh Road, Lucknow",
    contact: "+918400040004",
    locality: "Lucknow",
    company: "Tech Mahindra",
    emergencyName: "Anita Shah",
    emergencyContact: "+919111223344",
    emergencyRelation: "Mother",
    createdOn: "15-04-2025",
    name: "Vikram Shah",
    leadType: "walk-in", // mockType: walk-in
    enquiryStage: "Enquiry",
    lastUpdated: "18-04-2025",
    callTag: "Warm",
    staff: "Raj",
    profileImage: "https://randomuser.me/api/portraits/men/19.jpg",
  },
];

export const membershipData = [
  {
    title: "Gold Max Membership",
    duration: "3 months",
    features: [
      "Access to certain packages",
      "Priority support",
      "Discount on services",
    ],
    icon: <FaCrown />,
  },
  {
    title: "Silver Flex Membership",
    duration: "1 month",
    features: ["Basic access to services", "No long-term commitment"],
    icon: <FaCrown />,
  },
  {
    title: "Platinum Elite Membership",
    duration: "6 months",
    features: [
      "Full access to premium packages",
      "Free personal trainer sessions",
      "Exclusive invites to events",
    ],
    icon: <FaCrown />,
  },
  {
    title: "Platinum Elite Membership",
    duration: "6 months",
    features: [
      "Full access to premium packages",
      "Free personal trainer sessions",
      "Exclusive invites to events",
    ],
    icon: <FaCrown />,
  },
];

export const lostFoundData = [
  {
    id: 1,
    item: "Bottle",
    status: "Lost",
    date: "23-Apr-2025",
    description: "Blue color transparent water bottle of capacity 1ltr",
    itemImage: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 2,
    item: "Wallet",
    status: "Found",
    date: "24-Apr-2025",
    description: "Black leather wallet containing ID and some cash",
    itemImage: "https://randomuser.me/api/portraits/men/20.jpg",
  },
  {
    id: 3,
    item: "Umbrella",
    status: "Lost",
    date: "25-Apr-2025",
    description: "Red foldable umbrella with white dots",
    itemImage: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: 4,
    item: "Phone",
    status: "Lost",
    date: "22-Apr-2025",
    description: "Black iPhone 12 with a cracked screen",
    itemImage: "https://randomuser.me/api/portraits/men/30.jpg",
  },
  {
    id: 5,
    item: "Notebook",
    status: "Found",
    date: "21-Apr-2025",
    description: "Spiral-bound notebook with math notes",
    itemImage: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: 6,
    item: "Backpack",
    status: "Lost",
    date: "26-Apr-2025",
    description: "Grey laptop backpack with a company logo",
    itemImage: "https://randomuser.me/api/portraits/men/35.jpg",
  },
  {
    id: 7,
    item: "Keys",
    status: "Found",
    date: "20-Apr-2025",
    description: "Set of keys with a red keychain labeled 'Gym'",
    itemImage: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    id: 8,
    item: "Watch",
    status: "Lost",
    date: "18-Apr-2025",
    description: "Silver analog wristwatch with a black leather strap",
    itemImage: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 9,
    item: "Earbuds",
    status: "Found",
    date: "19-Apr-2025",
    description: "White wireless earbuds in a charging case",
    itemImage: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    id: 10,
    item: "Glasses",
    status: "Lost",
    date: "17-Apr-2025",
    description: "Black-rimmed prescription glasses",
    itemImage: "https://randomuser.me/api/portraits/women/40.jpg",
  },
  {
    id: 11,
    item: "Calculator",
    status: "Found",
    date: "16-Apr-2025",
    description: "Casio scientific calculator left in library",
    itemImage: "https://randomuser.me/api/portraits/men/50.jpg",
  },
];

export const trainerAvailability = {
  shivakar: [
    { date: "2025-05-07", time: "10:00:00" },
    { date: "2025-05-07", time: "14:00:00" },
  ],
  esha: [
    { date: "2025-05-07", time: "09:00:00" },
    { date: "2025-05-07", time: "16:00:00" },
  ],
};

export const todaySessions = [
  {
    id: 1,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 2,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 3,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 4,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 5,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 6,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 7,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 8,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 9,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
  {
    id: 10,
    name: "Ravi Rajput",
    contact: "987654****",
    time: "07:30AM",
    statusOptions: ["Scheduled", "Completed", "Cancelled"],
    selectedStatus: "",
  },
];

export const servicesList = [
  { value: "membership plan", label: "Membership Plan" },
  { value: "personal training", label: "Personal Training" },
  { value: "thrive membership fee", label: "Thrive Membership Fee" },
  {
    value: "corporate wellness activations",
    label: "Corporate Wellness Activations",
  },
  { value: "miscellaneous fee", label: "Miscellaneous Fee" },
  { value: "nutrition packages", label: "Nutrition Packages" },
];

export const sampleProducts = [
  {
    id: 1,
    productName: "Membership Plan",
    shortDescription: "6 Days Per week. Valid for 6 month(s).",
    servicesDuration: "6 months plan",
    amount: "100",
    sessions: "NA",
    month: 6,
  },
  {
    id: 2,
    productName: "Membership Plan",
    shortDescription: "1 Day Per week. Valid for 12 month(s).",
    servicesDuration: "12 months plan",
    amount: "200",
    sessions: "NA",
    month: 12,
  },
  {
    id: 3,
    productName: "Membership Plan",
    shortDescription: "6 Days Per week. Valid for 13 month(s).	",
    servicesDuration: "12 Months Promotional Plan",
    amount: "300",
    sessions: "NA",
    month: 13,
  },
];

export const productsByType = {
  "membership plan": [
    {
      id: 1,
      productName: "Membership Plan",
      shortDescription: "6 Days Per week. Valid for 6 month(s).",
      servicesDuration: "6 months plan",
      amount: 100,
      sessions: "NA",
      month: 6,
    },
    {
      id: 2,
      productName: "Membership Plan",
      shortDescription: "1 Day Per week. Valid for 12 month(s).",
      servicesDuration: "12 months plan",
      amount: 200,
      sessions: "NA",
      month: 12,
    },
    {
      id: 3,
      productName: "Membership Plan",
      shortDescription: "6 Days Per week. Valid for 13 month(s).",
      servicesDuration: "12 Months Promotional Plan",
      amount: 300,
      sessions: "NA",
      month: 13,
    },
  ],

  "personal training": [
    {
      id: 4,
      productName: "Personal Training",
      shortDescription: "10 Session Pack – 1-on-1 training",
      servicesDuration: "10 sessions plan",
      amount: 500,
      sessions: "NA",
      month: 3,
    },
    {
      id: 5,
      productName: "Personal Training",
      shortDescription: "20 Session Pack – 1-on-1 training",
      servicesDuration: "20 sessions plan",
      amount: 900,
      sessions: "NA",
      month: 6,
    },
  ],

  "thrive membership fee": [
    {
      id: 6,
      productName: "Thrive Membership Fee",
      shortDescription: "Thrive Monthly Subscription",
      servicesDuration: "1 month",
      amount: 150,
      sessions: "NA",
      month: 1,
    },
  ],

  "corporate wellness activations": [
    {
      id: 7,
      productName: "Corporate Wellness",
      shortDescription: "One-time corporate workshop session",
      servicesDuration: "1-day event",
      amount: 1200,
      sessions: "NA",
      month: 0,
    },
    {
      id: 8,
      productName: "Corporate Wellness",
      shortDescription: "Weekly sessions for 3 months",
      servicesDuration: "12 sessions",
      amount: 3000,
      sessions: "NA",
      month: 3,
    },
  ],

  "miscellaneous fee": [
    {
      id: 9,
      productName: "Miscellaneous Fee",
      shortDescription: "Locker Rental Fee – Monthly",
      servicesDuration: "1 month",
      amount: 50,
      sessions: "NA",
      month: 1,
    },
    {
      id: 10,
      productName: "Miscellaneous Fee",
      shortDescription: "Late Payment Fee",
      servicesDuration: "One-time",
      amount: 25,
      sessions: "NA",
      month: 0,
    },
  ],

  "nutrition packages": [
    {
      id: 11,
      productName: "Nutrition Package",
      shortDescription: "Basic Meal Plan Consultation (4 Weeks)",
      servicesDuration: "1 month",
      amount: "250",
      sessions: "NA",
      month: 1,
    },
    {
      id: 12,
      productName: "Nutrition Package",
      shortDescription: "3-Month Meal Coaching Program",
      servicesDuration: "3 months",
      amount: "700",
      sessions: "NA",
      month: 3,
    },
  ],
};

export const servicesData = [
  {
    id: 1,
    title: "Cricket",
    type: "cricket",
    category: "Sports",
    description:
      "Experience the thrill of cricket with our premium pitches, professional-grade equipment, and expert coaching.",
    price: 300,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 2,
    title: "Pickleball",
    type: "pickleball",
    category: "Sports",
    description:
      "Try out one of the fastest growing sports with top-quality pickleball courts and gear.",
    price: 250,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 3,
    title: "Tennis",
    type: "tennis",
    category: "Sports",
    description:
      "Play on professionally maintained tennis courts. We offer coaching sessions, match play, and equipment rentals.",
    price: 350,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 4,
    title: "Table Tennis",
    type: "table tennis",
    category: "Sports",
    description:
      "Challenge your reflexes with fast-paced table tennis games in our indoor facilities.",
    price: 150,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 5,
    title: "Football",
    type: "football",
    category: "Sports",
    description:
      "Join our 5-a-side and full-field football matches in high-quality turf arenas.",
    price: 400,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 6,
    title: "Basketball",
    type: "basketball",
    category: "Sports",
    description:
      "Shoot hoops at our professional basketball courts with high-quality equipment and flooring.",
    price: 280,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 7,
    title: "Badminton",
    type: "badminton",
    category: "Sports",
    description:
      "Play on indoor badminton courts with high-grade shuttlecocks and rackets available.",
    price: 220,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 8,
    title: "Swimming",
    type: "swimming",
    category: "Sports",
    description:
      "Enjoy lap swimming or take lessons in our temperature-controlled indoor pool.",
    price: 350,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 9,
    title: "Skating",
    type: "skating",
    category: "Sports",
    description:
      "Roll into action at our smooth skating rink with rentals and music sessions.",
    price: 180,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 10,
    title: "Yoga",
    type: "yoga",
    category: "GX", // Yoga as part of GX (Group Exercise)
    description:
      "Relax and rejuvenate with guided yoga classes for all levels, including Hatha, Vinyasa, and more.",
    price: 200,
    images: [
      "https://img3.khelomore.com/venues/71/images/1040x490/Ryder-DLF-4.jpg",
      "https://corvuss.in/wp-content/uploads/5.jpeg",
      "https://cms-tc.pbskids.org/global/Practice-Being-a-Good-Sport-Mezz-Image-908x510.jpg",
    ],
  },
  {
    id: 11,
    title: "Personal Training",
    type: "pt",
    category: "Trainers",
    description:
      "Get one-on-one guidance with certified personal trainers for customized fitness plans.",
    price: 500,
    images: [
      "https://cdn.pixabay.com/photo/2016/11/21/12/59/personal-trainer-1840884_1280.jpg",
    ],
  },
  {
    id: 12,
    title: "Strength Coaching",
    type: "nc",
    category: "Trainers",
    description:
      "Build muscle and strength under the supervision of experienced strength coaches.",
    price: 450,
    images: [
      "https://cdn.pixabay.com/photo/2017/01/31/20/23/dumbbell-2022066_1280.jpg",
    ],
  },
  {
    id: 13,
    title: "Weight Loss Coach",
    type: "nc",
    category: "Trainers",
    description:
      "Effective fat-loss programs with nutritional tracking and fitness routines.",
    price: 400,
    images: [
      "https://cdn.pixabay.com/photo/2014/12/03/20/32/weight-loss-556673_1280.jpg",
    ],
  },
  {
    id: 14,
    title: "Rehabilitation Training",
    type: "spa",
    category: "Trainers",
    description:
      "Injury recovery and mobility support with professional physiotherapy trainers.",
    price: 600,
    images: [
      "https://cdn.pixabay.com/photo/2017/02/02/15/15/knee-2031424_1280.jpg",
    ],
  },
  {
    id: 15,
    title: "Online Coaching",
    type: "salon",
    category: "Trainers",
    description:
      "Remote fitness training sessions via video with personalized feedback.",
    price: 300,
    images: [
      "https://cdn.pixabay.com/photo/2016/11/18/21/42/video-call-1834295_1280.jpg",
    ],
  },

  {
    id: 16,
    title: "Zumba",
    type: "zumba",
    category: "GX",
    subCategory: "Group Class",
    description:
      "Dance your way to fitness with fun and energetic Zumba group classes.",
    price: 250,
    images: [
      "https://cdn.pixabay.com/photo/2020/10/23/04/49/zumba-5678829_1280.jpg",
    ],
  },
  {
    id: 17,
    title: "Pilates",
    type: "pilates",
    category: "GX",
    subCategory: "Group Class",
    description:
      "Strengthen your core and improve posture in our group Pilates sessions.",
    price: 300,
    images: [
      "https://cdn.pixabay.com/photo/2016/11/21/13/59/woman-1847758_1280.jpg",
    ],
  },
  {
    id: 18,
    title: "Dance Event",
    type: "dance",
    category: "GX",
    subCategory: "Event",
    description:
      "Join our energetic dance event — perfect for fun and fitness.",
    price: 280,
    images: [
      "https://cdn.pixabay.com/photo/2016/11/29/05/08/people-1867129_1280.jpg",
    ],
  },
  {
    id: 19,
    title: "Makeup Workshop",
    type: "makeup",
    category: "GX",
    subCategory: "Event",
    description: "Learn professional makeup techniques in our weekend events.",
    price: 320,
    images: [
      "https://cdn.pixabay.com/photo/2016/07/12/23/36/makeup-1513699_1280.jpg",
    ],
  },
  {
    id: 20,
    title: "Makeup Workshop",
    type: "makeup",
    category: "GX",
    subCategory: "Event",
    description: "Learn professional makeup techniques in our weekend events.",
    price: 320,
    images: [
      "https://cdn.pixabay.com/photo/2016/07/12/23/36/makeup-1513699_1280.jpg",
    ],
  },
];

export const slotAvailability = {
  "2025-05-21": {
    "06:00": { status: "booked", service: "Cricket" },
    "08:00": { status: "booked", service: "Tennis" },
    "11:00": { status: "booked", service: "Pickleball" },
    "14:00": { status: "booked", service: "Table-tennis" },
    "18:00": { status: "booked", service: "Tennis" },
  },
  "2025-05-22": {
    "05:00": { status: "booked", service: "Pickleball" },
    "08:00": { status: "booked", service: "Cricket" },
    "10:00": { status: "booked", service: "Tennis" },
    "14:00": { status: "booked", service: "Table-tennis" },
    "18:00": { status: "booked", service: "Pickleball" },
  },
};
